// GENERATED FILE - DO NOT EDIT. Built by tools/house_tex_prep.js from
// assets/house/ (CC0: Poly Haven + ambientCG; see CREDITS.md). The files live
// under media/tex/house/ (hash-in-filename); loading starts at script eval and
// every consumer waits on img.complete/onload, so a material is built with
// whatever has arrived and updates itself when the rest lands.
//
// THE MATERIAL LIBRARY OF THE WOODEN HOUSE (G230). `tile` is metres of
// building per repeat and the generator's UVs are in metres, so the consumer
// sets repeat = 1/tile and nothing is hand-scaled. `paint` sets carry a
// NEUTRAL map (hue removed, luminance re-based) so that map * color is the
// paint colour at any hue. `ribbed` sets contain their own corrugation and
// suppress the roof's drawn standing seams.
const HOUSE_TEX_SETS = (typeof Image !== 'undefined') ? (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  const mk = src => { const i = new Image(); i.src = B + src; return i; };
  return {
    boxprof: { kind: 'roof', name: 'box-profile metal sheet', tile: 3.2, px: 1024, metal: 0.55, ribbed: true,
      diff: mk('media/tex/house/boxprof_diff_1k.5fcf796f.jpg'),
      nor: mk('media/tex/house/boxprof_nor_gl_1k.3bd81dcb.jpg'),
      rough: mk('media/tex/house/boxprof_rough_1k.9b4dff19.jpg'),
      paint: mk('media/tex/house/boxprof_paint_1k.880de2e0.jpg') },
    corrworn: { kind: 'roof', name: 'worn corrugated iron', tile: 3.6, px: 1024, metal: 0.5, ribbed: true,
      diff: mk('media/tex/house/corrworn_diff_1k.8bb5af63.jpg'),
      nor: mk('media/tex/house/corrworn_nor_gl_1k.4ab412e0.jpg'),
      rough: mk('media/tex/house/corrworn_rough_1k.db77f31e.jpg'),
      paint: null },
    corrrust: { kind: 'roof', name: 'rusty corrugated iron', tile: 4.8, px: 1024, metal: 0.35, ribbed: true,
      diff: mk('media/tex/house/corrrust_diff_1k.603509c0.jpg'),
      nor: mk('media/tex/house/corrrust_nor_gl_1k.9c720ddd.jpg'),
      rough: mk('media/tex/house/corrrust_rough_1k.af0a75f7.jpg'),
      paint: null },
    shingle: { kind: 'roof', name: 'shakes / shingles', tile: 2.6, px: 1024, metal: 0, ribbed: false,
      diff: mk('media/tex/house/shingle_diff_1k.b3d380b8.jpg'),
      nor: mk('media/tex/house/shingle_nor_gl_1k.66b175ba.jpg'),
      rough: mk('media/tex/house/shingle_rough_1k.efbf7428.jpg'),
      paint: null },
    galv: { kind: 'roof', name: 'galvanised sheet', tile: 1, px: 256, metal: 0.85, ribbed: false,
      diff: mk('media/tex/house/galv_diff_256.3f02ba2a.jpg'),
      nor: mk('media/tex/house/galv_nor_gl_256.87587c3c.jpg'),
      rough: mk('media/tex/house/galv_rough_256.19f4bffe.jpg'),
      paint: null },
    rust: { kind: 'roof', name: 'rusted steel', tile: 1.8, px: 512, metal: 0.6, ribbed: false,
      diff: mk('media/tex/house/rust_diff_512.5658a31a.jpg'),
      nor: mk('media/tex/house/rust_nor_gl_512.cfec3f33.jpg'),
      rough: mk('media/tex/house/rust_rough_512.ec911b97.jpg'),
      paint: null },
    shakes: { kind: 'plank', name: 'shake siding', tile: 2.2, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/shakes_diff_512.9269babd.jpg'),
      nor: mk('media/tex/house/shakes_nor_gl_512.0e41c74d.jpg'),
      rough: mk('media/tex/house/shakes_rough_512.b75347e9.jpg'),
      paint: null },
    paintwood: { kind: 'plank', name: 'painted planks', tile: 1.9, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/paintwood_diff_512.b2991f90.jpg'),
      nor: mk('media/tex/house/paintwood_nor_gl_512.51644d54.jpg'),
      rough: mk('media/tex/house/paintwood_rough_512.81dc84c9.jpg'),
      paint: mk('media/tex/house/paintwood_paint_512.7b6539a4.jpg') },
    greenwood: { kind: 'plank', name: 'rough painted planks', tile: 1.9, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/greenwood_diff_512.e71a8488.jpg'),
      nor: mk('media/tex/house/greenwood_nor_gl_512.6fa2f93b.jpg'),
      rough: mk('media/tex/house/greenwood_rough_512.2185d6ba.jpg'),
      paint: mk('media/tex/house/greenwood_paint_512.d30f740e.jpg') },
    board: { kind: 'plank', name: 'long boards', tile: 1.9, px: 512, metal: 0, ribbed: false, punch: 0,
      diff: mk('media/tex/house/board_diff_512.3ce5558b.jpg'),
      nor: mk('media/tex/house/board_nor_gl_512.721e862f.jpg'),
      rough: mk('media/tex/house/board_rough_512.d1f73b37.jpg'),
      paint: mk('media/tex/house/board_paint_512.9cb02843.jpg') },
    roughwood: { kind: 'plank', name: 'rough sawn planks', tile: 1.9, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/roughwood_diff_512.1236f9aa.jpg'),
      nor: mk('media/tex/house/roughwood_nor_gl_512.ac29d562.jpg'),
      rough: mk('media/tex/house/roughwood_rough_512.10ac362c.jpg'),
      paint: null },
    brownwood: { kind: 'plank', name: 'planed planks', tile: 1.9, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/brownwood_diff_512.1525f1ad.jpg'),
      nor: mk('media/tex/house/brownwood_nor_gl_512.c8765f5c.jpg'),
      rough: mk('media/tex/house/brownwood_rough_512.59b1bae3.jpg'),
      paint: null },
    greywood: { kind: 'plank', name: 'weathered grey planks', tile: 2.1, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/greywood_diff_512.ae643c55.jpg'),
      nor: mk('media/tex/house/greywood_nor_gl_512.a659eeab.jpg'),
      rough: mk('media/tex/house/greywood_rough_512.be803611.jpg'),
      paint: null },
    wornwood: { kind: 'plank', name: 'weathered brown planks', tile: 2.1, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/wornwood_diff_512.9a8f5894.jpg'),
      nor: mk('media/tex/house/wornwood_nor_gl_512.f367b54a.jpg'),
      rough: mk('media/tex/house/wornwood_rough_512.b57b34d8.jpg'),
      paint: null },
    deckwood: { kind: 'plank', name: 'decking boards', tile: 2.2, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/deckwood_diff_512.cde8704e.jpg'),
      nor: mk('media/tex/house/deckwood_nor_gl_512.93021499.jpg'),
      rough: mk('media/tex/house/deckwood_rough_512.dfbc533d.jpg'),
      paint: null },
    darkwood: { kind: 'plank', name: 'dark weathered planks', tile: 1.9, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/darkwood_diff_512.94cd2a26.jpg'),
      nor: mk('media/tex/house/darkwood_nor_gl_512.eec4e087.jpg'),
      rough: mk('media/tex/house/darkwood_rough_512.4ee3f6ed.jpg'),
      paint: mk('media/tex/house/darkwood_paint_512.a45a341b.jpg') },
    veneer: { kind: 'veneer', name: 'pale veneer', tile: 0.9, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/veneer_diff_256.863751b2.jpg'),
      nor: mk('media/tex/house/veneer_nor_gl_256.351e588d.jpg'),
      rough: mk('media/tex/house/veneer_rough_256.0a765a4a.jpg'),
      paint: mk('media/tex/house/veneer_paint_256.9e2833b2.jpg') },
    veneerdark: { kind: 'veneer', name: 'figured veneer', tile: 0.9, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/veneerdark_diff_256.64d891e6.jpg'),
      nor: mk('media/tex/house/veneerdark_nor_gl_256.579fd596.jpg'),
      rough: mk('media/tex/house/veneerdark_rough_256.9b3519fd.jpg'),
      paint: mk('media/tex/house/veneerdark_paint_256.d78c1f79.jpg') },
    veneerwarm: { kind: 'veneer', name: 'warm veneer', tile: 0.9, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/veneerwarm_diff_256.89ae0dc3.jpg'),
      nor: mk('media/tex/house/veneerwarm_nor_gl_256.7e69d023.jpg'),
      rough: mk('media/tex/house/veneerwarm_rough_256.5ce6c564.jpg'),
      paint: mk('media/tex/house/veneerwarm_paint_256.78f6afba.jpg') },
    veneerpale: { kind: 'veneer', name: 'pale laminate', tile: 0.9, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/veneerpale_diff_256.99593336.jpg'),
      nor: mk('media/tex/house/veneerpale_nor_gl_256.ea0d4b7d.jpg'),
      rough: mk('media/tex/house/veneerpale_rough_256.e3ec4a26.jpg'),
      paint: mk('media/tex/house/veneerpale_paint_256.45fea902.jpg') },
    stain: { kind: 'plank', name: 'dark stained boards', tile: 1.9, px: 512, metal: 0, ribbed: false, tint: false,
      diff: mk('media/tex/house/stain_diff_512.bd4e8765.jpg'),
      nor: mk('media/tex/house/stain_nor_gl_512.a686a315.jpg'),
      rough: mk('media/tex/house/stain_rough_512.b4fecd9a.jpg'),
      paint: null },
    bark: { kind: 'log', name: 'bark', tile: 1.1, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/bark_diff_256.5ca7f47f.jpg'),
      nor: mk('media/tex/house/bark_nor_gl_256.d2fe81d0.jpg'),
      rough: mk('media/tex/house/bark_rough_256.94b8bb60.jpg'),
      paint: null },
    feverbark: { kind: 'log', name: 'fever tree bark', tile: 1.1, px: 256, metal: 0, ribbed: false,
      diff: mk('media/tex/house/feverbark_diff_256.406b9c10.jpg'),
      nor: mk('media/tex/house/feverbark_nor_gl_256.bff131ce.jpg'),
      rough: mk('media/tex/house/feverbark_rough_256.6b87bb7c.jpg'),
      paint: null },
    rough: { kind: 'plain', name: 'rough sawn timber', tile: 1.3, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/rough_diff_512.a05ceb5c.jpg'),
      nor: mk('media/tex/house/rough_nor_gl_512.33cef1a2.jpg'),
      rough: mk('media/tex/house/rough_rough_512.6c3e8b82.jpg'),
      paint: null },
    mossy: { kind: 'plain', name: 'mossy timber', tile: 1.3, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/mossy_diff_512.fae026ea.jpg'),
      nor: mk('media/tex/house/mossy_nor_gl_512.3772ec85.jpg'),
      rough: mk('media/tex/house/mossy_rough_512.befee238.jpg'),
      paint: null },
    concrete: { kind: 'stone', name: 'damaged concrete', tile: 2.8, px: 1024, metal: 0, ribbed: false,
      diff: mk('media/tex/house/concrete_diff_1k.3790bb7c.jpg'),
      nor: mk('media/tex/house/concrete_nor_gl_1k.cac3c527.jpg'),
      rough: mk('media/tex/house/concrete_rough_1k.89083eec.jpg'),
      paint: null },
    concretec: { kind: 'stone', name: 'coarse dark concrete', tile: 2.8, px: 1024, metal: 0, ribbed: false,
      diff: mk('media/tex/house/concretec_diff_1k.c88d00ba.jpg'),
      nor: mk('media/tex/house/concretec_nor_gl_1k.9087b0b2.jpg'),
      rough: mk('media/tex/house/concretec_rough_1k.78d2900a.jpg'),
      paint: null },
    endgrain: { kind: 'end', name: 'log ends', tile: 1.25, px: 512, metal: 0, ribbed: false,
      diff: mk('media/tex/house/endgrain_diff_512.1480e59c.jpg'),
      nor: mk('media/tex/house/endgrain_nor_gl_512.cf642e59.jpg'),
      rough: mk('media/tex/house/endgrain_rough_512.9a7921ef.jpg'),
      paint: null },
  };
})() : null;

// THE CAPTURED SKIES (G234). `env` is an RGBE equirectangle - four bytes a
// pixel, mantissa and a shared exponent - so the consumer decodes it with a
// canvas and one exp2 per pixel and hands the floats to PMREM. `sun` is a
// unit vector in the same frame the equirect is sampled in
// (dir = (sin0 sin0, cos0, sin0 cos0), u running -pi..pi), `direct` the share
// of the sphere's light that arrives from the sun rather than from the dome,
// and every colour is the measured mean of that part of the sphere.
const HOUSE_SKIES = (typeof Image !== 'undefined') ? (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  const mk = src => { const i = new Image(); i.src = B + src; return i; };
  return {
    alps: { name: 'alps afternoon', w: 512, h: 256, sun: [0.4378, 0.6702, 0.5994], sunCol: [1, 0.974, 0.933], direct: 0.6991, ev: 1.441,
      hor: [0.089, 0.091, 0.062], gnd: [0.083, 0.083, 0.039], zen: [0.098, 0.143, 0.254],
      env: mk('media/tex/house/sky_alps_env_512.e5f254cc.png'), bg: mk('media/tex/house/sky_alps_bg_2k.66c5bf8d.jpg') },
    grassland: { name: 'grassland sunset', w: 512, h: 256, sun: [0.5725, 0.1065, 0.813], sunCol: [1, 0.224, 0.048], direct: 0.061, ev: 1.854,
      hor: [0.611, 0.325, 0.263], gnd: [0.066, 0.078, 0.046], zen: [0.321, 0.514, 0.788],
      env: mk('media/tex/house/sky_grassland_env_512.f0699e25.png'), bg: mk('media/tex/house/sky_grassland_bg_2k.78e3d24a.jpg') },
  };
})() : null;
