// GENERATED FILE - DO NOT EDIT. Built by tools/pavement_tex_prep.js from
// assets/pavement/ (fetched off Poly Haven by tools/pavement_tex_import.py),
// assets/airfield/ and assets/lot/ (CC0: Poly Haven, ambientCG; see CREDITS.md).
// The files live under media/tex/pavement/ (hash-in-filename); a map's Image
// is made when a consumer first reads it (a getter).
//
// THE PAVEMENT LIBRARY (roads & runways): the sets src/viewer/pavement.js
// draws roads and runways with - colour, normal, roughness, height, at 512 -
// KEYED BY SET; a page assembles the ones its recipe names into two texture
// arrays (PAVEMENT.library). `metres` is the texture's real size (the
// shader tiles by it); `mean` the set's mean colour (linear rgb 0-1) for
// the far tier and the tufts' feet; `role` what the class rows reach for.
const PAVEMENT_TEX_SETS = (typeof Image !== 'undefined') ? (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  const IM = {};
  const mk = src => IM[src] || (IM[src] = (() => { const i = new Image(); i.src = B + src; return i; })());
  return {
    concreteA: { name: "the WWII runway - damaged poured concrete", metres: 4.5, px: 512, role: 'base', mean: [0.0662,0.045,0.0276],
      get diff() { return mk('media/tex/pavement/concreteA_diff_512.46078ce4.jpg'); },
      get nor() { return mk('media/tex/pavement/concreteA_nor_gl_512.4739ca06.jpg'); },
      get rough() { return mk('media/tex/pavement/concreteA_rough_512.90679e59.jpg'); },
      get height() { return mk('media/tex/pavement/concreteA_height_512.8054d239.jpg'); } },
    concreteB: { name: "the runway broken up - the damage layer", metres: 3.5, px: 512, role: 'damage', mean: [0.1253,0.0942,0.0705],
      get diff() { return mk('media/tex/pavement/concreteB_diff_512.acf8e898.jpg'); },
      get nor() { return mk('media/tex/pavement/concreteB_nor_gl_512.12e519d4.jpg'); },
      get rough() { return mk('media/tex/pavement/concreteB_rough_512.db6594c0.jpg'); },
      get height() { return mk('media/tex/pavement/concreteB_height_512.013127df.jpg'); } },
    concreteM: { name: "moss on concrete - the edges and the joints", metres: 3, px: 512, role: 'moss', mean: [0.0982,0.0967,0.0134],
      get diff() { return mk('media/tex/pavement/concreteM_diff_512.0fb22657.jpg'); },
      get nor() { return mk('media/tex/pavement/concreteM_nor_gl_512.c5315b1a.jpg'); },
      get rough() { return mk('media/tex/pavement/concreteM_rough_512.fd5950bc.jpg'); },
      get height() { return mk('media/tex/pavement/concreteM_height_512.2f573683.jpg'); } },
    concreteD: { name: "dirty concrete - taxiway / apron", metres: 3, px: 512, role: 'base', mean: [0.2513,0.2296,0.1895],
      get diff() { return mk('media/tex/pavement/concreteD_diff_512.bb617b45.jpg'); },
      get nor() { return mk('media/tex/pavement/concreteD_nor_gl_512.f10a91f3.jpg'); },
      get rough() { return mk('media/tex/pavement/concreteD_rough_512.a255dc73.jpg'); },
      get height() { return mk('media/tex/pavement/concreteD_height_512.7dea616a.jpg'); } },
    asphaltW: { name: "worn asphalt - the road", metres: 2, px: 512, role: 'base', mean: [0.0614,0.0405,0.0281],
      get diff() { return mk('media/tex/pavement/asphaltW_diff_512.da194623.jpg'); },
      get nor() { return mk('media/tex/pavement/asphaltW_nor_gl_512.0fb05575.jpg'); },
      get rough() { return mk('media/tex/pavement/asphaltW_rough_512.c625ed25.jpg'); },
      get height() { return mk('media/tex/pavement/asphaltW_height_512.f5eed78f.jpg'); } },
    asphaltC: { name: "cracked asphalt - the road damaged", metres: 2.2, px: 512, role: 'damage', mean: [0.0673,0.0404,0.0266],
      get diff() { return mk('media/tex/pavement/asphaltC_diff_512.d5a619b5.jpg'); },
      get nor() { return mk('media/tex/pavement/asphaltC_nor_gl_512.c6610894.jpg'); },
      get rough() { return mk('media/tex/pavement/asphaltC_rough_512.f52db80e.jpg'); },
      get height() { return mk('media/tex/pavement/asphaltC_height_512.456c7bb7.jpg'); } },
    gravelR: { name: "a gravel road", metres: 2, px: 512, role: 'base', mean: [0.1923,0.0986,0.0508],
      get diff() { return mk('media/tex/pavement/gravelR_diff_512.6802d340.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelR_nor_gl_512.a88fdfc8.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelR_rough_512.1eba9518.jpg'); },
      get height() { return mk('media/tex/pavement/gravelR_height_512.4d18d0d1.jpg'); } },
    gravelK: { name: "rocky gravel - the shoulder band", metres: 1.81, px: 512, role: 'shoulder', mean: [0.1424,0.058,0.019],
      get diff() { return mk('media/tex/pavement/gravelK_diff_512.6120c28d.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelK_nor_gl_512.6e67ed24.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelK_rough_512.b9e9118d.jpg'); },
      get height() { return mk('media/tex/pavement/gravelK_height_512.55de9f8d.jpg'); } },
    gravelS: { name: "sandy gravel - the transition to sand", metres: 2.53, px: 512, role: 'base', mean: [0.3221,0.1719,0.0845],
      get diff() { return mk('media/tex/pavement/gravelS_diff_512.aa5661e4.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelS_nor_gl_512.c14d9d5d.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelS_rough_512.10735708.jpg'); },
      get height() { return mk('media/tex/pavement/gravelS_height_512.c0f812ec.jpg'); } },
    dirtP: { name: "park dirt - the dirt road", metres: 3, px: 512, role: 'base', mean: [0.1926,0.1292,0.0467],
      get diff() { return mk('media/tex/pavement/dirtP_diff_512.9939549e.jpg'); },
      get nor() { return mk('media/tex/pavement/dirtP_nor_gl_512.7d2b9f47.jpg'); },
      get rough() { return mk('media/tex/pavement/dirtP_rough_512.b5f149e2.jpg'); },
      get height() { return mk('media/tex/pavement/dirtP_height_512.411e0588.jpg'); } },
    tracksM: { name: "muddy tracks - the ruts", metres: 2.25, px: 512, role: 'tracks', mean: [0.0802,0.0291,0.0114],
      get diff() { return mk('media/tex/pavement/tracksM_diff_512.dd58bb05.jpg'); },
      get nor() { return mk('media/tex/pavement/tracksM_nor_gl_512.162f98a2.jpg'); },
      get rough() { return mk('media/tex/pavement/tracksM_rough_512.82695519.jpg'); },
      get height() { return mk('media/tex/pavement/tracksM_height_512.8ba69d29.jpg'); } },
    mudAir: { name: "aerial mud with tyre tracks - the cleared band", metres: 8, px: 512, role: 'tracks', mean: [0.0489,0.0398,0.0356],
      get diff() { return mk('media/tex/pavement/mudAir_diff_512.84009967.jpg'); },
      get nor() { return mk('media/tex/pavement/mudAir_nor_gl_512.4051be3a.jpg'); },
      get rough() { return mk('media/tex/pavement/mudAir_rough_512.95027c71.jpg'); },
      get height() { return mk('media/tex/pavement/mudAir_height_512.ac5a927b.jpg'); } },
    dirtAir: { name: "dirt from above - the macro tier", metres: 20, px: 512, role: 'macro', mean: [0.2055,0.1168,0.0547],
      get diff() { return mk('media/tex/pavement/dirtAir_diff_512.b89fcf64.jpg'); },
      get nor() { return mk('media/tex/pavement/dirtAir_nor_gl_512.743d42f7.jpg'); },
      get rough() { return mk('media/tex/pavement/dirtAir_rough_512.6d30d975.jpg'); },
      get height() { return mk('media/tex/pavement/dirtAir_height_512.397e13dc.jpg'); } },
    sandC: { name: "coast sand - the sand strip", metres: 3.94, px: 512, role: 'base', mean: [0.1133,0.0891,0.0517],
      get diff() { return mk('media/tex/pavement/sandC_diff_512.c491fcd1.jpg'); },
      get nor() { return mk('media/tex/pavement/sandC_nor_gl_512.f272fa16.jpg'); },
      get rough() { return mk('media/tex/pavement/sandC_rough_512.5ae4d4ca.jpg'); },
      get height() { return mk('media/tex/pavement/sandC_height_512.bd0a59c7.jpg'); } },
    gravelG: { name: "gravel ground - the grey gravel strip", metres: 3, px: 512, role: 'base', mean: [0.2896,0.2277,0.1406],
      get diff() { return mk('media/tex/pavement/gravelG_diff_512.520a980c.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelG_nor_gl_512.76767670.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelG_rough_512.4ad03bef.jpg'); },
      get height() { return mk('media/tex/pavement/gravelG_height_512.f365150b.jpg'); } },
    gravelF: { name: "fine grey gravel - the compacted wheel band", metres: 2, px: 512, role: 'base', mean: [0.4046,0.3836,0.3301],
      get diff() { return mk('media/tex/pavement/gravelF_diff_512.16231b93.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelF_nor_gl_512.e4c59c90.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelF_rough_512.bb7a8b6d.jpg'); },
      get height() { return mk('media/tex/pavement/gravelF_height_512.b802af8c.jpg'); } },
    gravelB: { name: "crushed dark stone - the strip edges", metres: 2, px: 512, role: 'shoulder', mean: [0.0788,0.0778,0.0734],
      get diff() { return mk('media/tex/pavement/gravelB_diff_512.29720f30.jpg'); },
      get nor() { return mk('media/tex/pavement/gravelB_nor_gl_512.ea407253.jpg'); },
      get rough() { return mk('media/tex/pavement/gravelB_rough_512.9b22f115.jpg'); },
      get height() { return mk('media/tex/pavement/gravelB_height_512.49730146.jpg'); } },
    rockG: { name: "rocky ground - the coarse patches of a gravel strip", metres: 3, px: 512, role: 'damage', mean: [0.1733,0.1494,0.1073],
      get diff() { return mk('media/tex/pavement/rockG_diff_512.7a842f21.jpg'); },
      get nor() { return mk('media/tex/pavement/rockG_nor_gl_512.8c4835e4.jpg'); },
      get rough() { return mk('media/tex/pavement/rockG_rough_512.cc1e0a66.jpg'); },
      get height() { return mk('media/tex/pavement/rockG_height_512.52dc0ac6.jpg'); } },
    dirtS: { name: "stony dirt path - the dirt road", metres: 2.17, px: 512, role: 'base', mean: [0.0658,0.037,0.0184],
      get diff() { return mk('media/tex/pavement/dirtS_diff_512.13d8449c.jpg'); },
      get nor() { return mk('media/tex/pavement/dirtS_nor_gl_512.9ae6ffd2.jpg'); },
      get rough() { return mk('media/tex/pavement/dirtS_rough_512.1106a950.jpg'); },
      get height() { return mk('media/tex/pavement/dirtS_height_512.127561be.jpg'); } },
    trailR: { name: "rocky trail - the dirt road coarse patches", metres: 2, px: 512, role: 'damage', mean: [0.2922,0.2182,0.1468],
      get diff() { return mk('media/tex/pavement/trailR_diff_512.a4d7f5c3.jpg'); },
      get nor() { return mk('media/tex/pavement/trailR_nor_gl_512.baafc1af.jpg'); },
      get rough() { return mk('media/tex/pavement/trailR_rough_512.f234afed.jpg'); },
      get height() { return mk('media/tex/pavement/trailR_height_512.38ea3d1c.jpg'); } },
    dirtG: { name: "plain dirt - the compacted wheel tracks", metres: 2, px: 512, role: 'tracks', mean: [0.1253,0.0851,0.0487],
      get diff() { return mk('media/tex/pavement/dirtG_diff_512.b598cc70.jpg'); },
      get nor() { return mk('media/tex/pavement/dirtG_nor_gl_512.df623c53.jpg'); },
      get rough() { return mk('media/tex/pavement/dirtG_rough_512.0f9ac2f6.jpg'); },
      get height() { return mk('media/tex/pavement/dirtG_height_512.8d91afbb.jpg'); } },
    grassG: { name: "meadow grass - the grass strip", metres: 2.51, px: 512, role: 'base', mean: [0.1563,0.1181,0.0483],
      get diff() { return mk('media/tex/pavement/grassG_diff_512.1188e448.jpg'); },
      get nor() { return mk('media/tex/pavement/grassG_nor_gl_512.aa1fb99a.jpg'); },
      get rough() { return mk('media/tex/pavement/grassG_rough_512.80037d2a.jpg'); },
      get height() { return mk('media/tex/pavement/grassG_height_512.2e323955.jpg'); } },
    grassP: { name: "worn grass with soil - the strip wheel tracks", metres: 1, px: 512, role: 'tracks', mean: [0.2729,0.2227,0.1287],
      get diff() { return mk('media/tex/pavement/grassP_diff_512.2aa44b97.jpg'); },
      get nor() { return mk('media/tex/pavement/grassP_nor_gl_512.8734fa23.jpg'); },
      get rough() { return mk('media/tex/pavement/grassP_rough_512.3e951b28.jpg'); },
      get height() { return mk('media/tex/pavement/grassP_height_512.cd968547.jpg'); } },
    grassS: { name: "sparse mossy grass - the strip rough patches", metres: 2, px: 512, role: 'damage', mean: [0.0796,0.0477,0.0078],
      get diff() { return mk('media/tex/pavement/grassS_diff_512.f550f134.jpg'); },
      get nor() { return mk('media/tex/pavement/grassS_nor_gl_512.6c263be1.jpg'); },
      get rough() { return mk('media/tex/pavement/grassS_rough_512.761d90a8.jpg'); },
      get height() { return mk('media/tex/pavement/grassS_height_512.d5535f04.jpg'); } },
    cracked: { name: "cracked concrete (the old runway look)", metres: 2.23, px: 512, role: 'base', mean: null,
      get diff() { return mk('media/tex/pavement/cracked_diff_512.2bec12e1.jpg'); },
      get nor() { return mk('media/tex/pavement/cracked_nor_gl_512.a1a37a91.jpg'); },
      get rough() { return mk('media/tex/pavement/cracked_rough_512.e6529d75.jpg'); },
      get height() { return mk('media/tex/pavement/cracked_height_512.a54d935f.jpg'); } },
    brushed: { name: "brushed concrete (the apron)", metres: 2, px: 512, role: 'base', mean: null,
      get diff() { return mk('media/tex/pavement/brushed_diff_512.25ee4dad.jpg'); },
      get nor() { return mk('media/tex/pavement/brushed_nor_gl_512.7820a130.jpg'); },
      get rough() { return mk('media/tex/pavement/brushed_rough_512.006fd4cf.jpg'); },
      get height() { return mk('media/tex/pavement/brushed_height_512.d3b19b0e.jpg'); } },
    asphalt: { name: "asphalt", metres: 3, px: 512, role: 'base', mean: null,
      get diff() { return mk('media/tex/pavement/asphalt_diff_512.5cc5ee99.jpg'); },
      get nor() { return mk('media/tex/pavement/asphalt_nor_gl_512.7a5097f4.jpg'); },
      get rough() { return mk('media/tex/pavement/asphalt_rough_512.ac02fc18.jpg'); },
      get height() { return mk('media/tex/pavement/asphalt_height_512.867f12b4.jpg'); } },
    asphaltaerial: { name: "asphalt from above (the macro tier)", metres: 30, px: 512, role: 'macro', mean: null,
      get diff() { return mk('media/tex/pavement/asphaltaerial_diff_512.35669471.jpg'); },
      get nor() { return mk('media/tex/pavement/asphaltaerial_nor_gl_512.a8df7943.jpg'); },
      get rough() { return mk('media/tex/pavement/asphaltaerial_rough_512.a5c0e524.jpg'); },
      get height() { return mk('media/tex/pavement/asphaltaerial_height_512.668287fd.jpg'); } },
    leafygrass: { name: "leafy grass (the rougher lawn)", metres: 2, px: 512, role: 'grass', mean: null,
      get diff() { return mk('media/tex/pavement/leafygrass_diff_512.5146f9d1.jpg'); },
      get nor() { return mk('media/tex/pavement/leafygrass_nor_gl_512.7b0b82a6.jpg'); },
      get rough() { return mk('media/tex/pavement/leafygrass_rough_512.0187dd5d.jpg'); },
      get height() { return mk('media/tex/pavement/leafygrass_height_512.7782c9e8.jpg'); } },
    fieldgrass: { name: "field grass (the strip)", metres: 2, px: 512, role: 'grass', mean: null,
      get diff() { return mk('media/tex/pavement/fieldgrass_diff_512.cce845e9.jpg'); },
      get nor() { return mk('media/tex/pavement/fieldgrass_nor_gl_512.34959b05.jpg'); },
      get rough() { return mk('media/tex/pavement/fieldgrass_rough_512.5497193f.jpg'); },
      get height() { return mk('media/tex/pavement/fieldgrass_height_512.4b0905a9.jpg'); } },
    lush: { name: "dense grass", metres: 2.4, px: 512, role: 'grass', mean: [0.0584,0.1065,0.0218],
      get diff() { return mk('media/tex/pavement/lush_diff_512.60992fc9.jpg'); },
      get nor() { return mk('media/tex/pavement/lush_nor_gl_512.f2bc4f10.jpg'); },
      get rough() { return mk('media/tex/pavement/lush_rough_512.8f65b07b.jpg'); },
      get height() { return mk('media/tex/pavement/lush_height_512.ea34602f.jpg'); } },
    grass: { name: "grass", metres: 2.4, px: 512, role: 'grass', mean: [0.119,0.1528,0.0305],
      get diff() { return mk('media/tex/pavement/grass_diff_512.9265fd54.jpg'); },
      get nor() { return mk('media/tex/pavement/grass_nor_gl_512.61ae6347.jpg'); },
      get rough() { return mk('media/tex/pavement/grass_rough_512.f5626b4f.jpg'); },
      get height() { return mk('media/tex/pavement/grass_height_512.5a801cde.jpg'); } },
    pebble: { name: "pebbles", metres: 4.5, px: 512, role: 'shoulder', mean: [0.2178,0.2034,0.1649],
      get diff() { return mk('media/tex/pavement/pebble_diff_512.40a4421d.jpg'); },
      get nor() { return mk('media/tex/pavement/pebble_nor_gl_512.69d75104.jpg'); },
      get rough() { return mk('media/tex/pavement/pebble_rough_512.d985d705.jpg'); },
      get height() { return mk('media/tex/pavement/pebble_height_512.f06ba062.jpg'); } },
    dry: { name: "dry ground (the cleared band)", metres: 2.2, px: 512, role: 'shoulder', mean: [0.3005,0.2486,0.1239],
      get diff() { return mk('media/tex/pavement/dry_diff_512.75fa2778.jpg'); },
      get nor() { return mk('media/tex/pavement/dry_nor_gl_512.f4f6e27d.jpg'); },
      get rough() { return mk('media/tex/pavement/dry_rough_512.8360b752.jpg'); },
      get height() { return mk('media/tex/pavement/dry_height_512.c822a8e1.jpg'); } },
    dirt: { name: "dirt path", metres: 1.8, px: 512, role: 'base', mean: [0.1326,0.1085,0.0826],
      get diff() { return mk('media/tex/pavement/dirt_diff_512.b7294a0a.jpg'); },
      get nor() { return mk('media/tex/pavement/dirt_nor_gl_512.e87f2d2e.jpg'); },
      get rough() { return mk('media/tex/pavement/dirt_rough_512.a924c560.jpg'); },
      get height() { return mk('media/tex/pavement/dirt_height_512.bd31ef00.jpg'); } },
  };
})() : null;
// the library's provenance, for CREDITS.md and the gate (never read at runtime)
const PAVEMENT_TEX_CREDITS = [{"key":"concreteA","source":"Poly Haven","slug":"damaged_concrete_floor","licence":"CC0","metres":4.5},{"key":"concreteB","source":"Poly Haven","slug":"damaged_concrete_floor_02","licence":"CC0","metres":3.5},{"key":"concreteM","source":"Poly Haven","slug":"concrete_moss","licence":"CC0","metres":3},{"key":"concreteD","source":"Poly Haven","slug":"dirty_concrete","licence":"CC0","metres":3},{"key":"asphaltW","source":"Poly Haven","slug":"worn_asphalt","licence":"CC0","metres":2},{"key":"asphaltC","source":"Poly Haven","slug":"road_damaged","licence":"CC0","metres":2.2},{"key":"gravelR","source":"Poly Haven","slug":"gravel_road","licence":"CC0","metres":2},{"key":"gravelK","source":"Poly Haven","slug":"rocky_gravel","licence":"CC0","metres":1.81},{"key":"gravelS","source":"Poly Haven","slug":"sandy_gravel_02","licence":"CC0","metres":2.53},{"key":"dirtP","source":"Poly Haven","slug":"park_dirt","licence":"CC0","metres":3},{"key":"tracksM","source":"Poly Haven","slug":"muddy_tracks","licence":"CC0","metres":2.25},{"key":"mudAir","source":"Poly Haven","slug":"aerial_mud_1","licence":"CC0","metres":8},{"key":"dirtAir","source":"Poly Haven","slug":"dirt_aerial_02","licence":"CC0","metres":20},{"key":"sandC","source":"Poly Haven","slug":"coast_sand_04","licence":"CC0","metres":3.94},{"key":"gravelG","source":"Poly Haven","slug":"gravel_ground_01","licence":"CC0","metres":3},{"key":"gravelF","source":"Poly Haven","slug":"gravel_floor_02","licence":"CC0","metres":2},{"key":"gravelB","source":"Poly Haven","slug":"gravel_stones","licence":"CC0","metres":2},{"key":"rockG","source":"Poly Haven","slug":"rock_ground_02","licence":"CC0","metres":3},{"key":"dirtS","source":"Poly Haven","slug":"stony_dirt_path","licence":"CC0","metres":2.17},{"key":"trailR","source":"Poly Haven","slug":"rocky_trail","licence":"CC0","metres":2},{"key":"dirtG","source":"Poly Haven","slug":"dirt","licence":"CC0","metres":2},{"key":"grassG","source":"Poly Haven","slug":"grass_ground","licence":"CC0","metres":2.51},{"key":"grassP","source":"Poly Haven","slug":"grass_path_2","licence":"CC0","metres":1},{"key":"grassS","source":"Poly Haven","slug":"sparse_grass","licence":"CC0","metres":2},{"key":"cracked","source":"Poly Haven","slug":"cracked_concrete_02","licence":"CC0","metres":2.23},{"key":"brushed","source":"Poly Haven","slug":"brushed_concrete_04","licence":"CC0","metres":2},{"key":"asphalt","source":"Poly Haven","slug":"asphalt_02","licence":"CC0","metres":3},{"key":"asphaltaerial","source":"Poly Haven","slug":"aerial_asphalt_01","licence":"CC0","metres":30},{"key":"leafygrass","source":"Poly Haven","slug":"leafy_grass","licence":"CC0","metres":2},{"key":"fieldgrass","source":"ambientCG","slug":"Grass005","licence":"CC0","metres":2},{"key":"lush","source":"ambientCG","slug":"Grass001","licence":"CC0","metres":2.4},{"key":"grass","source":"ambientCG","slug":"Grass004","licence":"CC0","metres":2.4},{"key":"pebble","source":"ambientCG","slug":"Gravel022","licence":"CC0","metres":4.5},{"key":"dry","source":"ambientCG","slug":"Ground081","licence":"CC0","metres":2.2},{"key":"dirt","source":"ambientCG","slug":"Ground110","licence":"CC0","metres":1.8}];
if (typeof module !== 'undefined' && module.exports) module.exports = { PAVEMENT_TEX_CREDITS };
