#!/usr/bin/env node
// fleet_spots.js - THE FLEET'S TIE-DOWN SPOTS on Jolene, printed (G2223, FLEET-PROPS A): every runway's ordered spots
// (25_airfield.js fleetSpots off the census's world: tools/_taxiclear_lib.js), what each refused, and the census's
// independent check (GATE TAXICLEAR 10) - its failing rows first.
//   node tools/fleet_spots.js [--json out.json] [--all] [--cook]
// --cook (G2225, FLEET-STAND): writes src/viewer/fleet_spots_pack.js - the spots the page stands the fleet on (the page
// has the shipped world but not the census's solid things, so the planner runs here, once, and the page reads its list);
// GATE TAXICLEAR 10 goes red when the pack is not a fresh census (re-run this after a premises or FLEET_SPOT change)
'use strict';
const fs = require('fs'), path = require('path');
const T = __dirname;
const PT = require(path.join(T, 'pilot_trace.js'));
PT.loadPanel();
const C = require(path.join(T, 'flight_core.js'));
const IN = require(path.join(T, 'island_node.js'));
const L = require(path.join(T, '_taxiclear_lib.js'));
const txt = fs.readFileSync(path.join(T, 'fixtures', 'island_jolene.json'), 'utf8');
const WI = IN.islandWorld('jolene', { premises: txt });
const SH = L.islandObstacles(C, 'jolene', 'town').concat(L.treeTrunks(WI)).concat(L.registryObstacles(WI));
const IX = L.index(SH);
const VB = L.BUILDS.map(B => { const def = C.buildGen(PT.specOf(B.key).spec); return Object.assign({}, B, { def, dims: L.buildDims(C, def) }); });
const foots = {}; for (const k in C.GP_PARKED_FOOT) { const f = C.GP_PARKED_FOOT[k]; foots[k] = { half: f[0], fwd: f[1], aft: f[2] }; }
foots.default = { half: C.GP_PARKED_DEFAULT[0], fwd: C.GP_PARKED_DEFAULT[1], aft: C.GP_PARKED_DEFAULT[2] };
const t0 = Date.now(), SC = L.spotCensus(C, WI, IX, VB, foots);
for (const p of SC.per) {
  console.log(p.id.padEnd(9) + String(p.n).padStart(3) + ' spots ' + p.kinds.padEnd(13) + ' refused ' + JSON.stringify(p.why));
  for (const s of p.spots) console.log('    ' + s.id.padEnd(22) + ' (' + s.x.toFixed(1) + ', ' + s.z.toFixed(1) + ') ry ' + s.ry.toFixed(3) + '  box ' + s.half.toFixed(2) + ' x ' + s.fwd.toFixed(2) + ' / ' + s.aft.toFixed(2));
}
const bad = SC.rows.filter(r => !r.ok);
console.log(SC.rows.length + ' census rows, ' + bad.length + ' failing, ' + ((Date.now() - t0) / 1000).toFixed(1) + ' s');
for (const r of (process.argv.includes('--all') ? SC.rows : bad).slice(0, 40)) console.log('  ' + (r.ok ? 'ok   ' : 'FAIL ') + r.id + ' ' + r.spot + ' [' + r.foot + '] ' + r.what + ' ' + (r.d != null ? r.d.toFixed(2) : '') + (r.need != null ? ' / ' + r.need.toFixed(2) : '') + ' ' + r.near);
const j = process.argv.indexOf('--json');
if (j > 0) fs.writeFileSync(process.argv[j + 1], JSON.stringify({ per: SC.per, bad }, null, 1));
if (process.argv.includes('--cook')) {
  const pack = L.spotPack(C, SC, 'jolene', 'town');
  const out = path.join(T, '..', 'src', 'viewer', 'fleet_spots_pack.js');
  fs.writeFileSync(out, [
    "// GENERATED by tools/fleet_spots.js --cook (G2225 FLEET-STAND) - do not edit. The fleet's tie-down spots on Jolene",
    "// (25_airfield.js fleetSpots off the taxi census's solid things, tools/_taxiclear_lib.js), per aerodrome in the planner's",
    '// order: [x, z, ry, id] in the world frame (the nose along (cos ry, -sin ry)). fleet_stand.js stands the fleet on them;',
    '// GATE TAXICLEAR 10 holds this file to a fresh census.',
    'window.FLEET_SPOTS_PACK = ' + JSON.stringify(pack) + ';', ''].join('\n'));
  console.log('cooked ' + path.relative(path.join(T, '..'), out).split(path.sep).join('/') + ': ' + Object.keys(pack.aero).map(k => k + ' ' + pack.aero[k].length).join(', '));
}
