#!/usr/bin/env node
// gameprem_shot.js - GAME-PREMISES (G2095): the PREMISES screen mock-up, drawn from the slice's own rules.
//
// Every number on the still is computed here by 71_player_bases.js over the v2 vintage fixture
// (tools/fixtures/player_v2_2026-10-06.json): the doors, the floor each hangar's aeroplanes take and where
// hangarPark stands them, the room left for a Cub, the offers' prices and rents, each aeroplane's place.
// Writes futureDesigns/game-premises/premises_data.js and shoots futureDesigns/game-premises/premises.html
// in headless Chromium (no WebGL: a static page, SwiftShader is irrelevant) - one still per selected base.
//
//   node tools/gameprem_shot.js                 -> premises_home.png, premises_w3.png
//   node tools/gameprem_shot.js --data-only     -> the data file alone
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm'), cp = require('child_process');
const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'futureDesigns', 'game-premises');
const C = require('./flight_core.js');
const packs = JSON.parse(fs.readFileSync(path.join(ROOT, 'src', 'props', 'props_packs.json'), 'utf8'));
const pctx = vm.createContext({ registerPropPack: C.registerPropPack, console });
for (const f of packs) vm.runInContext(fs.readFileSync(path.join(ROOT, 'src', 'props', f), 'utf8'), pctx, { filename: f });
const reg = C.PROP_REG, opts = { reg };

const raw = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'player_v2_2026-10-06.json'), 'utf8'));
const doc = C.playerNormalise(C.playerMigrate(JSON.parse(JSON.stringify(raw))));
const J = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'island_jolene.json'), 'utf8'));
const world = { aerodromes: J.layers.runways.map(r => ({ id: r.id, name: r.name, kind: +r.surface === 4 ? 'water' : 'strip' })) };
const nameOf = id => (world.aerodromes.find(a => a.id === id) || {}).name || id;
const CUB = (d => ({ half: d[0], fwd: d[1], aft: d[2] }))(C.GP_PARKED_FOOT.cub);

const hangar = id => {
  const s = doc.sheds[id], res = C.playerResidents(doc, id);
  const P = C.hangarPark(s, res.map(n => ({ name: n, foot: C.playerFootOf(doc, n) })), opts);
  const D = C.hangarDims(s), door = C.hangarDoor(s);
  const kits = Object.keys(C.HANGAR_KITS).filter(k => k !== 'park').map(k => ({
    key: k, name: C.HANGAR_KITS[k].name, on: (s.kits || []).includes(k), price: C.KIT_PRICES[k] || 0 }));
  return {
    id, name: s.name || (C.SHELLS[s.shell].name + ' · ' + nameOf(s.base)), shell: s.shell, shellName: C.SHELLS[s.shell].name,
    tenure: s.tenure, price: s.price || 0, rent: s.tenure === 'rent' ? Math.round((s.price || 0) * C.PREM_RATES.rentPerHour) : 0,
    dims: D, door, area: Math.round(P.area), used: Math.round(P.used), here: doc.here === id,
    roomCub: C.hangarRoomFor(s, CUB, res.map(n => ({ name: n, foot: C.playerFootOf(doc, n) })), opts),
    caps: C.hangarCaps(s), kits,
    plan: { HW: D.HW, HD: D.HD, obs: C.hangarObstacles(s, reg).map(o => [o.x0, o.x1, o.z0, o.z1].map(v => +v.toFixed(2))),
            planes: P.placed.map(p => ({ name: p.name, x: p.x, z: p.z, r: [p.rect.x0, p.rect.x1, p.rect.z0, p.rect.z1].map(v => +v.toFixed(2)),
                                         f: C.playerFootOf(doc, p.name) })) },
    residents: res,
  };
};
const bases = C.playerBaseIds(doc).map(b => ({
  id: b, name: nameOf(b), words: (C.BASE_OFFERS[b] || {}).words || '', hangars: C.playerHangarsAt(doc, b).map(hangar),
  out: Object.keys(doc.fleet).filter(n => { const w = C.playerWhere(doc, n); return w.kind === 'out' && w.aero === b; }),
}));
const offers = C.playerOffers(doc, world).filter(o => !o.held).map(o => Object.assign(o, { name: nameOf(o.aero) }));
const fleet = Object.keys(doc.fleet).sort().map(n => { const w = C.playerWhere(doc, n); return { name: n, kind: w.kind, hangar: w.hangar, aero: w.aero, at: nameOf(w.aero) }; });
const data = { wallet: doc.wallet, mode: doc.mode, clock: doc.clock, here: doc.here, bases, offers, fleet, ledger: doc.ledger.slice(-4),
               from: 'tools/gameprem_shot.js over tools/fixtures/player_v2_2026-10-06.json (71_player_bases.js)' };
fs.writeFileSync(path.join(OUT, 'premises_data.js'), '// GENERATED by tools/gameprem_shot.js - the rules\' own numbers over the v2 vintage\nwindow.PREM_DATA = ' + JSON.stringify(data, null, 1) + ';\n');
console.log('premises_data.js: ' + bases.length + ' bases, ' + offers.length + ' offers, ' + fleet.length + ' aeroplanes');
if (process.argv.includes('--data-only')) process.exit(0);

(async () => {
  let pw;
  try { pw = require('playwright'); } catch (e) { pw = require(path.join(cp.execSync('npm root -g').toString().trim(), 'playwright')); }
  const exe = fs.existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined;
  let browser;
  try { browser = await pw.chromium.launch({ headless: true }); }
  catch (e) { browser = await pw.chromium.launch({ headless: true, executablePath: exe }); }
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  for (const b of ['HOME', 'w3']) {
    await page.goto('file://' + path.join(OUT, 'premises.html') + '?base=' + b);
    await page.waitForFunction(() => window.PREM_READY === true, null, { timeout: 10000 });
    const f = path.join(OUT, 'premises_' + b.toLowerCase() + '.png');
    await page.screenshot({ path: f });
    console.log('shot ' + path.relative(ROOT, f));
  }
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
