#!/usr/bin/env python3
"""load_prep.py — bake the declared LOADS (tools/load_table.py): the freight's
own models and the camp / medevac dressing. FREIGHT-ASSETS, G2405.

Usage:  python tools/load_prep.py            (the whole table + the catalogue)
        python tools/load_prep.py --report   (inventory only, writes nothing)
Then:   node tools/prop_lod.js --kit loads   (the levels: the in-cabin _l1 ≤ 2k)
        node tools/ktx2_twins.js --family loads
        node tools/_load_check.js            (GATE LOADS)

It is tools/prop_prep.py's own runner pointed at a third table — the pier
kit's pattern (tools/pier_prep.py): the same as-is geometry, the same one
material, the same codec — with its own packs (src/loads/loads_*.js +
loads_packs.json) and its own media (media/geo/loads/, media/tex/loads/).
The hangar's registry, packs and media are not touched (GATE HANGAR would
refuse a prop no hangar kit claims).

THE CATALOGUE. After the bake, every CATALOGUE row (existing props and new)
is written to src/loads/loads_catalogue.json with its dims MEASURED off the
baked packs (props, pier and loads): [x, y, z] metres, y up, which is the
item's `dims` for FREIGHT-MODEL. A row naming a prop no pack holds is an error.
"""
import importlib.util, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import prop_prep                                     # noqa: E402
from media_lib import asset_src                      # noqa: E402

_spec = importlib.util.spec_from_file_location('load_table',
                                               os.path.join(HERE, 'load_table.py'))
TABLE = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(TABLE)

OUT = os.path.join(ROOT, 'src', 'loads')
CFG = dict(
    table=TABLE,
    src_dir=asset_src('assets/loads'),
    out_dir=OUT,
    geo='geo/loads', tex='tex/loads', prefix='loads_', packs='loads_packs.json',
    origin='assets/loads/, per the declared table in tools/load_table.py',
)
KINDS = ('crate', 'box', 'bag', 'drum', 'long', 'bulk')


def baked_dims():
    """key -> dim [x, y, z] for every FULL prop in the props, pier and loads
    packs, read out of the pack files the page loads (the JSON is the last
    argument of the registerPropPack wrapper)."""
    dims = {}
    for sub in ('props', 'pier', 'loads'):
        d = os.path.join(ROOT, 'src', sub)
        try:
            files = json.load(open(os.path.join(d, sub + '_packs.json')))
        except FileNotFoundError:
            continue
        for f in files:
            body = open(os.path.join(d, f), encoding='utf8').read()
            m = re.search(r'\}\)\((\{.*\})\)\);\s*$', body, re.S)
            if not m:
                continue
            for k, p in json.loads(m.group(1))['props'].items():
                if not p.get('lodOf'):
                    dims[k] = p['dim']
    return dims


def write_catalogue():
    dims = baked_dims()
    rows, bad = [], []
    for c in TABLE.CATALOGUE:
        if c['kind'] not in KINDS:
            bad.append('%s: kind %s' % (c['key'], c['kind']))
        if c['key'] not in dims:
            bad.append('%s: no baked prop of that key' % c['key'])
            continue
        rows.append(dict(c, dims=[round(v, 3) for v in dims[c['key']]]))
    if bad:
        raise SystemExit('catalogue: ' + '; '.join(bad))
    body = {'_': 'GENERATED by tools/load_prep.py from tools/load_table.py CATALOGUE; '
                 'dims [x, y(up), z] m measured off the baked packs',
            'kinds': list(KINDS), 'items': rows}
    with open(os.path.join(OUT, 'loads_catalogue.json'), 'w', encoding='utf8', newline='\n') as f:
        json.dump(body, f, indent=1)
        f.write('\n')
    for r in rows:
        print('  %-20s %-5s %4d kg  %5.2f x %5.2f x %5.2f m  %s'
              % (r['key'], r['kind'], r['kg'], *r['dims'], r['item']))
    print('catalogue: %d items -> src/loads/loads_catalogue.json' % len(rows))


if __name__ == '__main__':
    prop_prep.main(sys.argv[1:], CFG)
    if '--report' not in sys.argv[1:]:
        write_catalogue()
