#!/usr/bin/env node
// vendor_three.js — builds vendor/three.min.js from the npm package (W0.5a,
// 2026-09-13: r128 -> r186).
//
// WHY A BUILD STEP. three.js stopped shipping a UMD/global build at r160
// (build/three.min.js is gone; what ships is three.module.js + three.core.js
// and a CJS three.cjs). This project loads three as ONE classic script — a
// global `THREE` in every page (dev.html, index.html inlines it, the twenty
// bench pages) and a `require()` in every node gate that draws headless
// (_scene_headless.js, test_skinmat.js, ...). So the vendor file is bundled
// here: esbuild, IIFE, global name THREE, and a two-line footer that
//   (1) exports the same object for CommonJS, and
//   (2) THE COLOUR RULING. W0.5a shipped `ColorManagement.enabled = false`
//       here (a hex literal is the linear value the shader sees — the r128
//       reading every colour was tuned in). The same evening the user judged
//       the A/B and ruled MANAGED: three's own default (every hex decoded as
//       sRGB), with Cineon as the tone curve — so the footer no longer touches
//       the flag, and the pages' loaders read `flydiy.cm = '0'` to bring the
//       old reading back for the GRAPHICS menu's "as authored" step
//       (RENDERER-DECISION §4g / §4j).
//
// Usage:  cd flyDiy && npm install && node tools/vendor_three.js
//   (package.json pins three and esbuild; node_modules is gitignored; the
//    OUTPUT vendor/three.min.js is tracked, as it always was.)
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'vendor', 'three.min.js');

const esbuild = require(path.join(ROOT, 'node_modules', 'esbuild'));
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'three', 'package.json'), 'utf8'));
const rev = pkg.version.split('.')[1];

const entry = path.join(ROOT, 'node_modules', '.flydiy_three_entry.js');
fs.writeFileSync(entry, "export * from 'three';\n");

const banner = [
  `// three.js r${rev} (npm three@${pkg.version}) — MIT, © 2010-${new Date().getFullYear()} three.js authors.`,
  '// GENERATED by flyDiy/tools/vendor_three.js: esbuild IIFE bundle of three.module.js + three.core.js,',
  '// global THREE + CommonJS export. Do not edit; bump package.json and rebuild.',
].join('\n');
const footer = [
  '// flyDiy W0.5a: the same object for node gates (see tools/vendor_three.js; colour management is three\'s default, managed).',
  "if (typeof module !== 'undefined' && module.exports) module.exports = THREE;",
].join('\n');

const build = (entryFile, outfile) => esbuild.buildSync({
  entryPoints: [entryFile],
  bundle: true,
  format: 'iife',
  globalName: 'THREE',
  minify: true,
  legalComments: 'none',
  banner: { js: banner },
  footer: { js: footer },
  outfile,
  absWorkingDir: ROOT,
  logLevel: 'error',
});
build(entry, OUT);
fs.unlinkSync(entry);

// THE SECOND BUNDLE (W0.5b groundwork, §4h): the same global THREE, but the
// WebGPURenderer build (three/webgpu re-exports the whole core plus the node
// materials, PostProcessing and the renderer with its WebGL2 fallback backend)
// with the TSL functions under THREE.TSL. A page loads ONE of the two bundles —
// they are two builds of the same library and both claim `THREE`. Nothing in
// the game loads this one yet; tools/_tsl.html does.
const OUT_GPU = path.join(ROOT, 'vendor', 'three.webgpu.min.js');
const entryGpu = path.join(ROOT, 'node_modules', '.flydiy_three_webgpu_entry.js');
fs.writeFileSync(entryGpu, ["export * from 'three/webgpu';", "export * as TSL from 'three/tsl';", ''].join('\n'));
build(entryGpu, OUT_GPU);
fs.unlinkSync(entryGpu);

// prove it loads both ways
const T = require(OUT);
if (String(T.REVISION) !== rev) throw new Error(`built REVISION ${T.REVISION} != ${rev}`);
if (T.ColorManagement.enabled !== true) throw new Error('ColorManagement.enabled must be three\'s default (managed)');
console.log(`vendor/three.min.js: r${T.REVISION}, ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB, ColorManagement.enabled = ${T.ColorManagement.enabled}`);
const G = require(OUT_GPU);
if (typeof G.WebGPURenderer !== 'function' || typeof G.TSL.Fn !== 'function') throw new Error('webgpu bundle lacks WebGPURenderer / TSL');
console.log(`vendor/three.webgpu.min.js: r${G.REVISION}, ${(fs.statSync(OUT_GPU).size / 1024).toFixed(0)} KB, WebGPURenderer + THREE.TSL`);

// THE THIRD OUTPUT (AS3, G915): KTX2 / Basis Universal, LOADED ON DEMAND. vendor/ktx2/ holds
//   ktx2_loader.js           three@0.186's examples/jsm/loaders/KTX2Loader.js (+ its WorkerPool, ktx-parse and
//                            zstddec), bundled as a classic script that ADDS THREE.KTX2Loader to the page's global
//                            THREE ('three' resolves to that global, never a second copy of the library)
//   basis_transcoder.js      three@0.186's examples/jsm/libs/basis/ transcoder, copied byte for byte (the loader
//   basis_transcoder.wasm    starts it in Web Workers: the transcode never runs on the main thread)
// Nothing loads them at page load: src/viewer/ktx2.js appends the loader when a KTX2 file is first asked for
// (under the loading screen), and the loader fetches the transcoder into its workers.
const KTX2_DIR = path.join(ROOT, 'vendor', 'ktx2');
fs.mkdirSync(KTX2_DIR, { recursive: true });
const entryKtx2 = path.join(ROOT, 'node_modules', '.flydiy_ktx2_entry.js');
const shimKtx2 = path.join(ROOT, 'node_modules', '.flydiy_global_three.js');
fs.writeFileSync(shimKtx2, 'module.exports = THREE;\n');
fs.writeFileSync(entryKtx2, "import { KTX2Loader } from './three/examples/jsm/loaders/KTX2Loader.js';\nTHREE.KTX2Loader = KTX2Loader;\n");
esbuild.buildSync({
  entryPoints: [entryKtx2],
  bundle: true,
  format: 'iife',
  minify: true,
  legalComments: 'none',
  // the loader's DEFAULT transcoder URL is made from import.meta.url at module scope; the page always sets its
  // own path (setTranscoderPath), so the default only has to be a URL that parses
  define: { 'import.meta.url': '"http://localhost/flydiy-ktx2-unused/"' },
  // 'three' -> the page's global (a sync build takes no plugins: an alias to a one-line shim)
  alias: { three: './node_modules/.flydiy_global_three.js' },
  banner: { js: [
    `// three.js r${rev} KTX2Loader (npm three@${pkg.version}: examples/jsm/loaders/KTX2Loader.js + WorkerPool, ktx-parse, zstddec) - MIT.`,
    '// GENERATED by flyDiy/tools/vendor_three.js: a classic script that adds THREE.KTX2Loader to the global THREE. Do not edit.',
  ].join('\n') },
  outfile: path.join(KTX2_DIR, 'ktx2_loader.js'),
  absWorkingDir: ROOT,
  logLevel: 'error',
});
fs.unlinkSync(entryKtx2); fs.unlinkSync(shimKtx2);
for (const f of ['basis_transcoder.js', 'basis_transcoder.wasm'])
  fs.copyFileSync(path.join(ROOT, 'node_modules', 'three', 'examples', 'jsm', 'libs', 'basis', f), path.join(KTX2_DIR, f));
{ // prove it: the loader lands on a fresh THREE, and the transcoder is the package's
  const vm = require('vm');
  const ctx = { console, URL, TextDecoder };
  vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(OUT, 'utf8'), ctx);
  vm.runInContext(fs.readFileSync(path.join(KTX2_DIR, 'ktx2_loader.js'), 'utf8'), ctx);
  if (typeof ctx.THREE.KTX2Loader !== 'function') throw new Error('vendor/ktx2/ktx2_loader.js did not define THREE.KTX2Loader');
  console.log(`vendor/ktx2/: ktx2_loader.js ${(fs.statSync(path.join(KTX2_DIR, 'ktx2_loader.js')).size / 1024).toFixed(0)} KB, basis_transcoder.js + .wasm ${(fs.statSync(path.join(KTX2_DIR, 'basis_transcoder.wasm')).size / 1024).toFixed(0)} KB (three@${pkg.version})`);
}
