// generated by tools/model_prep.py — do not edit
// source: "FREE Cessna 172SP" by NLM (sketchfab.com/NLM-Group), CC-BY-4.0; extracted from free_cessna_172sp.glb by tools/glb_extract.py
// Geometry bytes in the bin file below (fetched via MODEL_LOAD/
// ASSET_FETCH; gates read it with fs); groups carry off/len into
// it. B re-roots the media paths for pages not at flyDiy/.
const MODEL_C172 = (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  return { v:5, bb:[-4.0313,0.0098,-5.4991,4.1975,2.6828,5.4991], hub:[-3.699,1.229,0],
  surfaces:[{name:"aileronG",drive:"da",sgn:-1,k:1,p:[-0.795,2.01,3.929],ax:[-0.1224,0.0479,0.9913],ramp:null},{name:"aileronD",drive:"da",sgn:1,k:1,p:[-0.795,2.01,-3.929],ax:[0.1224,-0.0479,0.9913],ramp:null},{name:"elevator",drive:"de",sgn:1,k:1,p:[3.263,1.296,0],ax:[0,0,1],ramp:null},{name:"rudder",drive:"dr",sgn:-1,k:1,p:[3.429,1.793,0],ax:[0.4109,0.9117,0],ramp:null},{name:"flapG",drive:"flap",sgn:-1,k:0.524,p:[-0.658,1.886,1.524],ax:[0,0.0826,0.9966],ramp:null},{name:"flapD",drive:"flap",sgn:-1,k:0.524,p:[-0.658,1.886,-1.524],ax:[0,-0.0826,0.9966],ramp:null},{name:"nosepant",drive:"dr",sgn:1,k:0.35,p:[-2.85,0.25,0],ax:[0,1,0],ramp:null},{name:"nosefork",drive:"dr",sgn:1,k:0.35,p:[-2.85,0.25,0],ax:[0,1,0],ramp:null},{name:"tyreN",drive:"dr",sgn:1,k:0.35,p:[-2.85,0.25,0],ax:[0,1,0],ramp:null},{name:"hubN",drive:"dr",sgn:1,k:0.35,p:[-2.85,0.25,0],ax:[0,1,0],ramp:null},{name:"noseaxle",drive:"dr",sgn:1,k:0.35,p:[-2.85,0.25,0],ax:[0,1,0],ramp:null}],
  bin:B+"media/geo/models/c172.7853e832.bin",
  mats:{skin:{tex:"skin",rough:0.2211,metal:0,nrm:"skin_nrm"},tyre:{tex:"tyre",rough:1,metal:1,mr:"tyre_mr"},metal:{tex:"metal",rough:0.1387,metal:1},front:{tex:"front",rough:1,metal:1,mr:"front_mr",nrm:"front_nrm"},pedal:{tex:"pedal",rough:0.298,metal:0},radio:{tex:"radio",rough:0.245,metal:1,emis:[1,1,1]},screen:{tex:"screen",rough:0.1929,metal:1,emis:[1,1,1]},dials:{tex:"dials",rough:0.5,metal:0,emis:[1,1,1]},gaugeA:{tex:"gaugeA",rough:1,metal:1,emis:[1,1,1]},gaugeB:{tex:"gaugeB",rough:1,metal:1,emis:[1,1,1]},gaugeC:{tex:"gaugeC",rough:0.245,metal:1,emis:[1,1,1]},glass:{tex:"glass",opacity:0.37,rough:0,metal:0},hub:{opacity:1,color:0xcccccc,rough:0,metal:0.4556},blades:{opacity:1,color:0x121212,rough:0.4739,metal:1,mr:"blades_mr"},prophub:{opacity:1,color:0xbcbcbc,rough:0.5,metal:0.4495},black:{opacity:1,color:0xa0a0a,rough:0.5,metal:0},gearmetal:{opacity:1,color:0x2e2e2e,rough:0.2971,metal:0.3636},cabin:{opacity:1,color:0x853817,rough:0.6385,metal:0},cabin2:{opacity:1,color:0x1a0f08,rough:0.5,metal:0.3215},panel:{opacity:1,color:0x141414,rough:0.5,metal:0.8955},cockpit:{opacity:1,color:0xb0b0b,rough:1,metal:0.1773,mr:"cockpit_mr"},chair:{opacity:1,color:0xa0a0a,rough:0.5,metal:0},trim:{opacity:1,color:0x1f1f1f,rough:0.5,metal:1},bezel:{opacity:1,color:0xd0d0d,rough:0.5,metal:0.1773},knob:{opacity:1,color:0x1a1a1a,rough:0.5,metal:0},yoke:{opacity:1,color:0xb0b0b0,rough:0.6,metal:0}},
  texs:{skin:B+"media/tex/models/c172/skin.31dbda12.png",
    tyre:B+"media/tex/models/c172/tyre.08379c30.png",
    metal:B+"media/tex/models/c172/metal.3ba9c597.png",
    front:B+"media/tex/models/c172/front.3996b1eb.png",
    pedal:B+"media/tex/models/c172/pedal.68cebdaa.png",
    radio:B+"media/tex/models/c172/radio.967eef88.jpg",
    screen:B+"media/tex/models/c172/screen.73633138.jpg",
    dials:B+"media/tex/models/c172/dials.81f4f76f.jpg",
    gaugeA:B+"media/tex/models/c172/gaugeA.d4e41f3b.jpg",
    gaugeB:B+"media/tex/models/c172/gaugeB.6c9374b0.jpg",
    gaugeC:B+"media/tex/models/c172/gaugeC.d1056f2f.jpg",
    glass:B+"media/tex/models/c172/glass.0c7014cb.png",
    skin_nrm:B+"media/tex/models/c172/skin_nrm.af76b415.jpg",
    tyre_mr:B+"media/tex/models/c172/tyre_mr.5fb387ce.jpg",
    front_mr:B+"media/tex/models/c172/front_mr.7e1455a6.jpg",
    front_nrm:B+"media/tex/models/c172/front_nrm.2e2dce62.jpg",
    blades_mr:B+"media/tex/models/c172/blades_mr.1b719ba6.jpg",
    cockpit_mr:B+"media/tex/models/c172/cockpit_mr.e172cbbf.jpg"},
  groups:{skin:{nv:35465,nt:57984,sid:1,mat:"skin",off:0,len:738027},glass:{nv:4990,nt:7680,sid:0,mat:"glass",off:738027,len:95988},tyre:{nv:19746,nt:28800,sid:1,mat:"tyre",off:834015,len:390014},hub:{nv:438,nt:576,sid:1,mat:"hub",off:1224029,len:8282},metal:{nv:10636,nt:16504,sid:0,mat:"metal",off:1232311,len:205392},gear:{nv:60,nt:64,sid:1,mat:"gearmetal",off:1437703,len:1052},prop:{nv:1886,nt:3200,sid:0,mat:"blades",off:1438755,len:38068},propface:{nv:272,nt:256,sid:0,mat:"prophub",off:1476823,len:4264},propcap:{nv:616,nt:896,sid:0,mat:"black",off:1481087,len:11544},proptip:{nv:1916,nt:3520,sid:0,mat:"metal",off:1492631,len:40288},cabin:{nv:12752,nt:19600,sid:0,mat:"cabin",off:1532919,len:245128},cabin2:{nv:18193,nt:30188,sid:0,mat:"cabin2",off:1778047,len:363066},glareshield:{nv:2158,nt:3648,sid:0,mat:"front",off:2141113,len:43476},pedals:{nv:666,nt:336,sid:0,mat:"pedal",off:2184589,len:8684},ipanel:{nv:124,nt:120,sid:0,mat:"panel",off:2193273,len:1968},icockpit:{nv:696,nt:680,sid:0,mat:"cockpit",off:2195241,len:11048},ichair:{nv:768,nt:656,sid:0,mat:"chair",off:2206289,len:11624},itrim:{nv:80,nt:80,sid:0,mat:"trim",off:2217913,len:1288},ibezel:{nv:5870,nt:7696,sid:0,mat:"bezel",off:2219201,len:104884},iknob:{nv:240,nt:256,sid:0,mat:"knob",off:2324085,len:3944},iyoke:{nv:360,nt:360,sid:0,mat:"yoke",off:2328029,len:5768},iradio:{nv:288,nt:144,sid:0,mat:"radio",off:2333797,len:3752},iscreen:{nv:8,nt:4,sid:0,mat:"screen",off:2337549,len:112},idials:{nv:111,nt:108,sid:0,mat:"dials",off:2337661,len:1766},igaugeA:{nv:688,nt:864,sid:0,mat:"gaugeA",off:2339427,len:12072},igaugeB:{nv:628,nt:864,sid:0,mat:"gaugeB",off:2351499,len:11472},igaugeC:{nv:424,nt:540,sid:0,mat:"gaugeC",off:2362971,len:7488}} };
})();
if (typeof module !== 'undefined') module.exports = { MODEL_C172 };
