// generated by tools/ref_prep.py — do not edit
// source: "Fokker Eindecker E.III" by helijah (Emmanuel BARANGER), CC-BY-4.0; https://sketchfab.com/3d-models/fokker-eindecker-eiii-bf1ab0a7b7a64f5d9a825ac2fddf35dd — baked by tools/ref_prep.py, geometry as delivered, base-colour maps declined (see the tool)
// REFERENCE ONLY: no control surfaces, no propeller hub, no skin
//   binding. This payload is never flown — it stands beside the
//   build in the garage (src/viewer/refplane.js).
// The geometry bytes live in the bin file below (fetched via
//   MODEL_LOAD/ASSET_FETCH; the gates read it with fs); groups carry
//   off/len into it. B re-roots the media paths for pages that do
//   not live at flyDiy/ (see tools/_media_lib.js).
const MODEL_EIII = (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  return { v:5, ref:1, lic:"CC-BY-4.0",
  credit:"\"Fokker Eindecker E.III\" by helijah (Emmanuel BARANGER), CC-BY-4.0; https://sketchfab.com/3d-models/fokker-eindecker-eiii-bf1ab0a7b7a64f5d9a825ac2fddf35dd \u2014 baked by tools/ref_prep.py, geometry as delivered, base-colour maps declined (see the tool)",
  bb:[-3.5884,-1.1974,-4.7225,3.5834,1.4782,4.7225],
  bin:B+"media/geo/models/eiii.ba6a01e6.bin",
  mats:{DefaultWhite:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_texture_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_interior_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_compass_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_tach_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_turn_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_asi_png:{color:0xffffff,rough:0.6,metal:0.0},DefaultWhite_alt_png:{color:0xffffff,rough:0.6,metal:0.0},transparent:{color:0xe7e7e7,opacity:0.15,rough:0.6,metal:0.0},DefaultWhite_panel_png:{color:0xffffff,rough:0.6,metal:0.0},transparentExt:{color:0xe7e7e7,opacity:0.3,rough:0.6,metal:0.0}},
  texs:{},
  groups:{DefaultWhite:{nv:65535,nt:67200,sid:0,mat:"DefaultWhite",off:0,len:1058558},DefaultWhite__2:{nv:6725,nt:6502,sid:0,mat:"DefaultWhite",off:1058558,len:106270},DefaultWhite_texture_png:{nv:10443,nt:14138,sid:0,mat:"DefaultWhite_texture_png",off:1164828,len:189266},DefaultWhite_interior_png:{nv:2691,nt:4138,sid:0,mat:"DefaultWhite_interior_png",off:1354094,len:51746},DefaultWhite_compass_png:{nv:1801,nt:2554,sid:0,mat:"DefaultWhite_compass_png",off:1405840,len:33342},DefaultWhite_tach_png:{nv:1134,nt:1601,sid:0,mat:"DefaultWhite_tach_png",off:1439182,len:20954},DefaultWhite_turn_png:{nv:759,nt:1286,sid:0,mat:"DefaultWhite_turn_png",off:1460136,len:15314},DefaultWhite_asi_png:{nv:603,nt:628,sid:0,mat:"DefaultWhite_asi_png",off:1475450,len:9806},DefaultWhite_alt_png:{nv:484,nt:501,sid:0,mat:"DefaultWhite_alt_png",off:1485256,len:7854},transparent:{nv:150,nt:144,sid:0,mat:"transparent",off:1493110,len:2372},DefaultWhite_panel_png:{nv:50,nt:40,sid:0,mat:"DefaultWhite_panel_png",off:1495482,len:748},transparentExt:{nv:28,nt:36,sid:0,mat:"transparentExt",off:1496230,len:504}} };
})();
if (typeof module !== 'undefined') module.exports = { MODEL_EIII };
