// generated by tools/model_prep.py — do not edit
// source: pa18 by BARANGER Emmanuel (helijah), GPL, for FlightGear; livery Brett Harrison 2010; Sketchfab listing (skfb.ly/NvEt) CC-BY 4.0
// Geometry bytes in the bin file below (fetched via MODEL_LOAD/
// ASSET_FETCH; gates read it with fs); groups carry off/len into
// it. B re-roots the media paths for pages not at flyDiy/.
const MODEL_PA18 = (() => {
  const B = (typeof FLYDIY_ASSET_BASE !== 'undefined') ? FLYDIY_ASSET_BASE : '';
  return { v:5, bb:[-3.4959,-1.3516,-5.3566,3.4291,1.3478,5.3566], hub:[-3.371,-0.0705,0],
  surfaces:[{name:"aileronG",drive:"da",sgn:-1,k:1,p:[-0.718,0.62,0],ax:[0,0,1],ramp:null},{name:"aileronD",drive:"da",sgn:1,k:1,p:[-0.718,0.62,0],ax:[0,0,1],ramp:null},{name:"profondeur",drive:"de",sgn:1,k:1,p:[2.834,0.292,0],ax:[0,0,1],ramp:null},{name:"direction",drive:"dr",sgn:-1,k:1,p:[2.905,0,0],ax:[0,1,0],ramp:[2.85,2.95]},{name:"roueA",drive:"dr",sgn:-1,k:0.5,p:[3.14,-0.1,0],ax:[0,1,0],ramp:null},{name:"voletG",drive:"flap",sgn:-1,k:0.87,p:[-0.824,0.592,0],ax:[0,0,1],ramp:null},{name:"voletD",drive:"flap",sgn:-1,k:0.87,p:[-0.824,0.592,0],ax:[0,0,1],ramp:null}],
  bin:B+"media/geo/models/pa18.5cd30285.bin",
  mats:{skin:{tex:"skin"},glass:{opacity:0.28,color:0xaad4ea},cabin:{tex:"cabin"},seat:{tex:"seat"},panel:{tex:"panel"},ai:{tex:"ai"},asi:{tex:"asi"},alt:{tex:"alt"},turn:{tex:"turn"},hdg:{tex:"hdg"},vsi:{tex:"vsi"},covers:{opacity:0.15}},
  texs:{skin:B+"media/tex/models/pa18/skin.cd0eab0d.jpg",
    cabin:B+"media/tex/models/pa18/cabin.4aeaa281.jpg",
    seat:B+"media/tex/models/pa18/seat.39173374.jpg",
    panel:B+"media/tex/models/pa18/panel.6778fc62.jpg",
    ai:B+"media/tex/models/pa18/ai.e14cf3fb.jpg",
    asi:B+"media/tex/models/pa18/asi.78262284.png",
    alt:B+"media/tex/models/pa18/alt.dcaa48e1.jpg",
    turn:B+"media/tex/models/pa18/turn.8d5f71e8.jpg",
    hdg:B+"media/tex/models/pa18/hdg.52f59882.jpg",
    vsi:B+"media/tex/models/pa18/vsi.c5ce3728.jpg"},
  groups:{skin:{nv:15993,nt:26941,sid:1,mat:"skin",off:0,len:337577},glass:{nv:91,nt:112,sid:0,mat:"glass",off:337577,len:1590},prop:{nv:144,nt:200,sid:0,mat:"skin",off:339167,len:2648},cabin:{nv:229,nt:336,sid:0,mat:"cabin",off:341815,len:4314},seat:{nv:1460,nt:2200,sid:0,mat:"seat",off:346129,len:27808},panel:{nv:227,nt:254,sid:0,mat:"panel",off:373937,len:3802},gauge_ai:{nv:744,nt:1095,sid:0,mat:"ai",off:377739,len:14018},gauge_asi:{nv:249,nt:334,sid:0,mat:"asi",off:391757,len:4502},gauge_alt:{nv:529,nt:737,sid:0,mat:"alt",off:396259,len:9720},gauge_turn:{nv:355,nt:532,sid:0,mat:"turn",off:405979,len:6750},gauge_hdg:{nv:318,nt:272,sid:0,mat:"hdg",off:412729,len:4820},gauge_vsi:{nv:249,nt:334,sid:0,mat:"vsi",off:417549,len:4502},covers:{nv:189,nt:183,sid:0,mat:"covers",off:422051,len:2996}} };
})();
if (typeof module !== 'undefined') module.exports = { MODEL_PA18 };
