// tools/build.js — the ONLY writer of version.json and trunk/version.js (20 §8).
// A hand edit of either is a gate failure (assertion V1).
//
// Also runs the full gate and records the static section to gate-report.json, so
// the dev panel can display checks that can only run against a filesystem.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { GENOME_V, BRIDGE_V, ECOLOGY_V } from '../contracts/versions.js';

const ROOT = new URL('..', import.meta.url).pathname;
const p = (...a) => join(ROOT, ...a);

// ── version ──────────────────────────────────────────────────────────────────
const bump = process.argv.includes('--minor') ? 'minor'
           : process.argv.includes('--major') ? 'major' : 'patch';

let [maj, min, pat] = [0, 0, 0];
if (existsSync(p('version.json'))) {
  const prev = JSON.parse(readFileSync(p('version.json'), 'utf8'));
  [maj, min, pat] = prev.app.split('.').map(Number);
}
if (bump === 'major') { maj++; min = 0; pat = 0; }
else if (bump === 'minor') { min++; pat = 0; }
else pat++;

let commit = 'uncommitted';
try { commit = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch {}

const VERSION = {
  app: `${maj}.${min}.${pat}`,
  build: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
  commit,
  genome: GENOME_V, bridge: BRIDGE_V, ecology: ECOLOGY_V,
};

writeFileSync(p('version.json'), JSON.stringify(VERSION, null, 2) + '\n');
writeFileSync(p('trunk/version.js'),
`// trunk/version.js — GENERATED by tools/build.js. Do not edit.
// A hand edit is a gate failure (V1). The three schema versions are declared in
// contracts/versions.js and mirrored here; APP_V is produced by the build.
export const VERSION = ${JSON.stringify(VERSION, null, 2)};
export const APP_V = ${JSON.stringify(VERSION.app)};
export default VERSION;
`);
console.log(`version.json  ${VERSION.app}  ${commit}`);

// ── gate ─────────────────────────────────────────────────────────────────────
const { runStaticGate } = await import('../gate/trunk.js');
const stat = runStaticGate();
writeFileSync(p('gate-report.json'), JSON.stringify({ ...stat, appV: VERSION.app, commit }, null, 2) + '\n');
console.log(`gate-report.json  ${stat.passed} passed, ${stat.failed} failed`);

if (stat.failed > 0) {
  console.error('\nSTATIC GATE RED — build not fit to ship. Run `npm run gate` for detail.');
  process.exit(1);
}
