// trunk/version.js — GENERATED by tools/build.js. Do not edit.
// A hand edit is a gate failure (V1). The three schema versions are declared in
// contracts/versions.js and mirrored here; APP_V is produced by the build.
export const VERSION = {
  "app": "0.8.1",
  "build": "2026-07-29T23:56:49Z",
  "commit": "uncommitted",
  "genome": 2,
  "bridge": 4,
  "ecology": 1
};
export const APP_V = "0.8.1";
export default VERSION;
