// trunk/version.js — GENERATED by tools/build.js. Do not edit.
// A hand edit is a gate failure (V1). The three schema versions are declared in
// contracts/versions.js and mirrored here; APP_V is produced by the build.
export const VERSION = {
  "app": "0.8.9",
  "build": "2026-08-06T22:27:37Z",
  "commit": "59a1345",
  "genome": 5,
  "bridge": 6,
  "ecology": 1
};
export const APP_V = "0.8.9";
export default VERSION;
