// GENERATED by tools/gameprem_shot.js - the rules' own numbers over the v2 vintage
window.PREM_DATA = {
 "wallet": 41250,
 "mode": "career",
 "clock": 18450,
 "here": "w3",
 "bases": [
  {
   "id": "HOME",
   "name": "Jolene AFB 13/31",
   "words": "Jolene AFB · the WWII field",
   "hangars": [
    {
     "id": "HOME",
     "name": "Home hangar",
     "shell": "club",
     "shellName": "Club hangar",
     "tenure": "own",
     "price": 0,
     "rent": 0,
     "dims": {
      "HW": 15,
      "HD": 12.5,
      "EAVE": 7
     },
     "door": {
      "w": 25,
      "h": 5.6
     },
     "area": 750,
     "used": 103,
     "here": false,
     "roomCub": 1,
     "caps": [
      "park",
      "handwork",
      "wood",
      "tube",
      "metal",
      "composite",
      "engine",
      "avionics",
      "paperwork",
      "store",
      "handling",
      "warm",
      "heavy"
     ],
     "kits": [
      {
       "key": "bench",
       "name": "Workbench",
       "on": true,
       "price": 800
      },
      {
       "key": "wood",
       "name": "Woodshop",
       "on": true,
       "price": 2500
      },
      {
       "key": "metal",
       "name": "Metalshop",
       "on": true,
       "price": 3500
      },
      {
       "key": "store",
       "name": "Stores",
       "on": true,
       "price": 300
      },
      {
       "key": "handling",
       "name": "Handling",
       "on": true,
       "price": 600
      },
      {
       "key": "office",
       "name": "Office corner",
       "on": true,
       "price": 1500
      },
      {
       "key": "comfort",
       "name": "Comfort",
       "on": true,
       "price": 900
      },
      {
       "key": "curio",
       "name": "Curios",
       "on": true,
       "price": 0
      },
      {
       "key": "wip",
       "name": "Work in progress",
       "on": true,
       "price": 0
      }
     ],
     "plan": {
      "HW": 15,
      "HD": 12.5,
      "obs": [
       [
        -6.01,
        -3.6,
        13.43,
        14.57
       ],
       [
        -5.52,
        -4.1,
        14.85,
        14.91
       ],
       [
        1.79,
        3.21,
        -14.91,
        -14.85
       ],
       [
        -3.27,
        -2.88,
        12.7,
        13.1
       ],
       [
        2.12,
        2.5,
        -13.25,
        -12.85
       ],
       [
        6.68,
        7.36,
        13.85,
        14.25
       ],
       [
        0.14,
        0.82,
        -14.35,
        -13.95
       ],
       [
        -6.77,
        -5.13,
        -14.7,
        -12.98
       ],
       [
        -4.75,
        -2.04,
        -14.7,
        -12.54
       ],
       [
        -1.65,
        -0.27,
        -14.7,
        -13.44
       ],
       [
        -6.33,
        -1.94,
        -11.59,
        -8.01
       ],
       [
        -11.66,
        -10.65,
        -11.61,
        -11.19
       ],
       [
        -11.55,
        -11.14,
        -10.51,
        -10.09
       ],
       [
        -10.59,
        -10.18,
        -8.61,
        -8.19
       ],
       [
        -11.56,
        -10.55,
        -7.61,
        -7.19
       ],
       [
        11.19,
        11.61,
        -9.34,
        -8.33
       ],
       [
        11.24,
        11.66,
        -9.95,
        -9.55
       ],
       [
        11.02,
        11.68,
        12.08,
        12.92
       ],
       [
        10.41,
        12.09,
        4.87,
        5.47
       ],
       [
        6.85,
        7.38,
        -14.35,
        -13.75
       ],
       [
        11.23,
        11.87,
        -12.49,
        -11.85
       ],
       [
        11.23,
        11.87,
        -13.15,
        -12.51
       ],
       [
        -1.04,
        -0.69,
        13.02,
        13.28
       ],
       [
        9.31,
        9.72,
        13.95,
        14.35
       ],
       [
        8.41,
        8.9,
        -14.39,
        -13.91
       ],
       [
        9.42,
        10.2,
        -14.38,
        -13.82
       ],
       [
        -10.55,
        -10.03,
        -11.29,
        -10.91
       ],
       [
        -11.16,
        -10.77,
        -9.26,
        -8.74
       ],
       [
        11.48,
        11.82,
        11.41,
        11.75
       ],
       [
        11.43,
        11.77,
        10.83,
        11.17
       ],
       [
        10.64,
        11.05,
        11.13,
        11.54
       ],
       [
        10.51,
        10.99,
        -12.74,
        -12.26
       ],
       [
        10.43,
        10.77,
        -11.72,
        -11.45
       ],
       [
        10.07,
        10.33,
        -12,
        -11.66
       ],
       [
        11.06,
        11.84,
        -2.94,
        -2.39
       ],
       [
        11.06,
        11.84,
        -3.77,
        -3.23
       ],
       [
        4.68,
        6.28,
        13.35,
        14.45
       ],
       [
        7.84,
        8.89,
        13.76,
        14.34
       ],
       [
        10.09,
        10.68,
        14.1,
        14.8
       ],
       [
        -8.75,
        -7.79,
        -11.35,
        -10.85
       ],
       [
        -11.69,
        -11.19,
        -5.81,
        -4.85
       ],
       [
        1.5,
        3.5,
        -14.57,
        -13.63
       ],
       [
        -2.68,
        -1.28,
        14.88,
        14.88
       ],
       [
        6.71,
        9.83,
        10.47,
        12.53
       ],
       [
        7.96,
        9.15,
        10.83,
        11.84
       ],
       [
        7.1,
        7.51,
        10.22,
        10.61
       ],
       [
        8.91,
        9.55,
        12.93,
        13.57
       ],
       [
        9.95,
        10.44,
        13.26,
        13.74
       ],
       [
        12.23,
        12.49,
        6.1,
        6.57
       ],
       [
        -2.53,
        -0.73,
        13.5,
        14.4
       ],
       [
        -11.71,
        -7.33,
        9.44,
        11.23
       ],
       [
        -5.92,
        -5.52,
        13.8,
        14
       ],
       [
        -4.47,
        -3.7,
        13.8,
        14.2
       ],
       [
        -11.36,
        -10.95,
        -11.61,
        -11.19
       ],
       [
        -2.21,
        -1.83,
        13.74,
        14.26
       ],
       [
        5,
        5.39,
        13.64,
        14.16
       ],
       [
        -10.58,
        -10.19,
        -11.31,
        -10.79
       ],
       [
        -11.32,
        -10.8,
        -9.14,
        -8.76
       ],
       [
        3.12,
        3.32,
        -14.16,
        -13.54
       ],
       [
        1.67,
        2.08,
        -14.05,
        -13.85
       ],
       [
        -4.09,
        -3.51,
        13.74,
        14.16
       ],
       [
        -1.36,
        -0.95,
        13.74,
        14.16
       ],
       [
        0.94,
        1.94,
        14.12,
        14.78
       ],
       [
        2,
        3,
        14.12,
        14.78
       ],
       [
        3.06,
        4.06,
        14.12,
        14.78
       ],
       [
        -1.65,
        -0.65,
        -14.78,
        -14.12
       ],
       [
        -2.71,
        -1.71,
        -14.78,
        -14.12
       ],
       [
        10.44,
        11.36,
        -13.8,
        -3.2
       ],
       [
        -9.65,
        -8.05,
        6.45,
        7.55
       ],
       [
        9.82,
        11.52,
        9.48,
        11.18
       ],
       [
        -11.27,
        -10.47,
        12.9,
        13.7
       ],
       [
        -11.94,
        -11.14,
        12,
        12.8
       ],
       [
        -11.55,
        -10.75,
        11.2,
        12
       ],
       [
        -11.36,
        -10.56,
        -8.4,
        -7.6
       ],
       [
        0.36,
        6.56,
        -10.97,
        -9.37
       ],
       [
        10.6,
        11,
        -4.6,
        4.6
       ],
       [
        -7.06,
        2.44,
        9.33,
        11.33
       ],
       [
        8.2,
        9.5,
        -5.98,
        -4.68
       ]
      ],
      "planes": [
       {
        "name": "Metal Cessna",
        "x": 3.812,
        "z": 1.317,
        "r": [
         1.81,
         10.41,
         -4.68,
         7.32
        ],
        "f": {
         "half": 5.5,
         "fwd": 1.5,
         "aft": 6.1,
         "h": 2.7
        }
       }
      ]
     },
     "residents": [
      "Metal Cessna"
     ]
    },
    {
     "id": "HOME.2",
     "name": "Works · Jolene AFB 13/31",
     "shell": "works",
     "shellName": "Works",
     "tenure": "own",
     "price": 15000,
     "rent": 0,
     "dims": {
      "HW": 20,
      "HD": 20,
      "EAVE": 9.5
     },
     "door": {
      "w": 35,
      "h": 6.4
     },
     "area": 1600,
     "used": 0,
     "here": false,
     "roomCub": 13,
     "caps": [
      "park",
      "tube",
      "metal",
      "engine",
      "handling",
      "heavy"
     ],
     "kits": [
      {
       "key": "bench",
       "name": "Workbench",
       "on": false,
       "price": 800
      },
      {
       "key": "wood",
       "name": "Woodshop",
       "on": false,
       "price": 2500
      },
      {
       "key": "metal",
       "name": "Metalshop",
       "on": true,
       "price": 3500
      },
      {
       "key": "store",
       "name": "Stores",
       "on": false,
       "price": 300
      },
      {
       "key": "handling",
       "name": "Handling",
       "on": true,
       "price": 600
      },
      {
       "key": "office",
       "name": "Office corner",
       "on": false,
       "price": 1500
      },
      {
       "key": "comfort",
       "name": "Comfort",
       "on": false,
       "price": 900
      },
      {
       "key": "curio",
       "name": "Curios",
       "on": false,
       "price": 0
      },
      {
       "key": "wip",
       "name": "Work in progress",
       "on": false,
       "price": 0
      }
     ],
     "plan": {
      "HW": 20,
      "HD": 20,
      "obs": [
       [
        18.52,
        19.18,
        16.25,
        17.09
       ],
       [
        17.91,
        19.59,
        6.59,
        7.19
       ],
       [
        11.12,
        11.65,
        -19.35,
        -18.75
       ],
       [
        18.73,
        19.37,
        -16.54,
        -15.9
       ],
       [
        18.73,
        19.37,
        -17.43,
        -16.79
       ],
       [
        7.97,
        9.57,
        18.35,
        19.45
       ],
       [
        12.86,
        13.91,
        18.76,
        19.34
       ],
       [
        16.32,
        16.91,
        19.1,
        19.8
       ],
       [
        -13.71,
        -12.75,
        -16.35,
        -15.85
       ],
       [
        -18.56,
        -18.06,
        -7.59,
        -6.63
       ],
       [
        1.81,
        2.81,
        19.12,
        19.78
       ],
       [
        3.5,
        4.5,
        19.12,
        19.78
       ],
       [
        5.19,
        6.19,
        19.12,
        19.78
       ],
       [
        -2.35,
        -1.35,
        -19.78,
        -19.12
       ],
       [
        -4.04,
        -3.04,
        -19.78,
        -19.12
       ]
      ],
      "planes": []
     },
     "residents": []
    }
   ],
   "out": [
    "Spare Jodel"
   ]
  },
  {
   "id": "w3",
   "name": "Tamgas Hill Strip",
   "words": "Tamgas Hill · a strip above the trees",
   "hangars": [
    {
     "id": "w3",
     "name": "Tamgas shed",
     "shell": "field",
     "shellName": "Field shed",
     "tenure": "rent",
     "price": 4800,
     "rent": 48,
     "dims": {
      "HW": 8.5,
      "HD": 9,
      "EAVE": 3.6
     },
     "door": {
      "w": 12,
      "h": 3.1
     },
     "area": 306,
     "used": 92,
     "here": true,
     "roomCub": 1,
     "caps": [
      "park",
      "handwork"
     ],
     "kits": [
      {
       "key": "bench",
       "name": "Workbench",
       "on": true,
       "price": 800
      },
      {
       "key": "wood",
       "name": "Woodshop",
       "on": false,
       "price": 2500
      },
      {
       "key": "metal",
       "name": "Metalshop",
       "on": false,
       "price": 3500
      },
      {
       "key": "store",
       "name": "Stores",
       "on": false,
       "price": 300
      },
      {
       "key": "handling",
       "name": "Handling",
       "on": false,
       "price": 600
      },
      {
       "key": "office",
       "name": "Office corner",
       "on": false,
       "price": 1500
      },
      {
       "key": "comfort",
       "name": "Comfort",
       "on": false,
       "price": 900
      },
      {
       "key": "curio",
       "name": "Curios",
       "on": false,
       "price": 0
      },
      {
       "key": "wip",
       "name": "Work in progress",
       "on": false,
       "price": 0
      }
     ],
     "plan": {
      "HW": 8.5,
      "HD": 9,
      "obs": [
       [
        -4.66,
        -2.26,
        6.93,
        8.07
       ],
       [
        -4.17,
        -2.75,
        8.35,
        8.41
       ],
       [
        1.09,
        2.51,
        -8.41,
        -8.35
       ],
       [
        -2.41,
        -2.02,
        6.2,
        6.6
       ],
       [
        1.47,
        1.85,
        -6.75,
        -6.35
       ],
       [
        4.71,
        5.4,
        7.35,
        7.75
       ],
       [
        0,
        0.69,
        -7.85,
        -7.45
       ],
       [
        -4.32,
        -3.92,
        7.3,
        7.5
       ],
       [
        -3.33,
        -2.56,
        7.3,
        7.7
       ]
      ],
      "planes": [
       {
        "name": "Jolene Cub",
        "x": 3,
        "z": 0,
        "r": [
         1.2,
         9,
         -5.9,
         5.9
        ],
        "f": {
         "half": 5.4,
         "fwd": 1.3,
         "aft": 5.5,
         "h": 2
        }
       }
      ]
     },
     "residents": [
      "Jolene Cub"
     ]
    }
   ],
   "out": []
  }
 ],
 "offers": [
  {
   "aero": "tw_ski",
   "plot": "tw_ski",
   "name": "Skyline Altiport",
   "words": "Skyline Altiport · snow, and a short slope",
   "held": false,
   "shells": [
    {
     "shell": "field",
     "price": 5400,
     "rent": 54
    },
    {
     "shell": "club",
     "price": 9000,
     "rent": 90
    }
   ],
   "kits": [
    "park"
   ],
   "water": false,
   "derelict": false
  },
  {
   "aero": "mn_strip",
   "plot": "mn_strip",
   "name": "Jumbo Mine Street",
   "words": "Jumbo Mine · a derelict shed on the street",
   "held": false,
   "shells": [
    {
     "shell": "field",
     "price": 3000,
     "rent": 30
    }
   ],
   "kits": [
    "park",
    "bench",
    "curio"
   ],
   "water": false,
   "derelict": true
  },
  {
   "aero": "SEA",
   "plot": "SEA",
   "name": "Annette Dock",
   "words": "Annette Dock · a slipway",
   "held": false,
   "shells": [
    {
     "shell": "field",
     "price": 6000,
     "rent": 60
    },
    {
     "shell": "club",
     "price": 10000,
     "rent": 100
    }
   ],
   "kits": [
    "park",
    "store"
   ],
   "water": true,
   "derelict": false
  },
  {
   "aero": "mk_sea",
   "plot": "mk_sea",
   "name": "Metlakatla Seaplane Base",
   "words": "Metlakatla · the seaplane float",
   "held": false,
   "shells": [
    {
     "shell": "field",
     "price": 4800,
     "rent": 48
    }
   ],
   "kits": [
    "park"
   ],
   "water": true,
   "derelict": false
  }
 ],
 "fleet": [
  {
   "name": "Jolene Cub",
   "kind": "in",
   "hangar": "w3",
   "aero": "w3",
   "at": "Tamgas Hill Strip"
  },
  {
   "name": "Metal Cessna",
   "kind": "in",
   "hangar": "HOME",
   "aero": "HOME",
   "at": "Jolene AFB 13/31"
  },
  {
   "name": "Spare Jodel",
   "kind": "out",
   "hangar": null,
   "aero": "HOME",
   "at": "Jolene AFB 13/31"
  },
  {
   "name": "Twin floats",
   "kind": "away",
   "hangar": null,
   "aero": "mk_sea",
   "at": "Metlakatla Seaplane Base"
  }
 ],
 "ledger": [
  {
   "k": "acquire",
   "amt": 15000,
   "ref": "HOME.2",
   "clock": 7200,
   "free": false
  },
  {
   "k": "rent",
   "amt": 307,
   "ref": null,
   "clock": 18450,
   "free": false
  }
 ],
 "from": "tools/gameprem_shot.js over tools/fixtures/player_v2_2026-10-06.json (71_player_bases.js)"
};
