/* sw.js — hors-ligne simple : precache + cache-first.
   Bosser CACHE à chaque livraison pour invalider l'ancien. */
const CACHE = "roboclash-v42";
const ASSETS = ["./","index.html","styles.css","data.js","engine.js","app.js",
                "manifest.webmanifest","favicon.ico",
                "assets/icons/icon-128.png","assets/icons/icon-144.png","assets/icons/icon-152.png","assets/icons/icon-167.png","assets/icons/icon-180.png","assets/icons/icon-192.png","assets/icons/icon-256.png","assets/icons/icon-32.png","assets/icons/icon-384.png","assets/icons/icon-48.png","assets/icons/icon-512.png","assets/icons/icon-64.png","assets/icons/icon-72.png","assets/icons/icon-96.png","assets/icons/maskable-192.png","assets/icons/maskable-512.png",
                "roboclash-ui.css",
                "assets/stickers/arena.webp","assets/stickers/chev_red.webp","assets/stickers/chev_tall.webp","assets/stickers/chev_yel.webp","assets/stickers/co2.webp","assets/stickers/crown.webp","assets/stickers/danger.webp","assets/stickers/f_angry.webp","assets/stickers/f_blank.webp","assets/stickers/f_ko.webp","assets/stickers/f_smile.webp","assets/stickers/first.webp","assets/stickers/hazard_worn.webp","assets/stickers/hotsurf.webp","assets/stickers/ir.webp","assets/stickers/lidar.webp","assets/stickers/mkii.webp","assets/stickers/nostep.webp","assets/stickers/p13.webp","assets/stickers/p23.webp","assets/stickers/push.webp","assets/stickers/saw.webp","assets/stickers/scr_blue.webp","assets/stickers/scr_gray.webp","assets/stickers/scr_hex.webp","assets/stickers/scr_orange.webp","assets/stickers/scr_red.webp","assets/stickers/scr_wr.webp","assets/stickers/season3.webp","assets/stickers/skull.webp","assets/stickers/star.webp","assets/stickers/stripe_rw.webp","assets/stickers/sumo.webp","assets/stickers/tally_k.webp","assets/stickers/tally_r.webp","assets/stickers/tally_w.webp","assets/stickers/target.webp","assets/stickers/top8.webp","assets/stickers/trn88.webp","assets/stickers/v0.webp","assets/stickers/v1.webp","assets/stickers/v2.webp","assets/stickers/v3.webp","assets/stickers/v4.webp","assets/stickers/v5.webp","assets/stickers/v6.webp","assets/stickers/v7.webp","assets/stickers/v8.webp","assets/stickers/v9.webp","assets/stickers/w_bang.webp","assets/stickers/w_crush.webp","assets/stickers/w_fire.webp","assets/stickers/w_gears.webp","assets/stickers/w_skull.webp","assets/fonts/monoton-400.woff2","assets/fonts/orbitron-500.woff2","assets/fonts/orbitron-700.woff2","assets/fonts/orbitron-900.woff2","assets/fonts/barlow-condensed-400.woff2","assets/fonts/barlow-condensed-500.woff2","assets/fonts/barlow-condensed-600.woff2","assets/fonts/barlow-condensed-700.woff2","assets/fonts/saira-condensed-500.woff2","assets/fonts/saira-condensed-600.woff2","assets/fonts/saira-condensed-700.woff2","assets/fonts/michroma-400.woff2","assets/fonts/press-start-2p-400.woff2","assets/fonts/audiowide-400.woff2",
  "assets/arena_s_nerd.webp","assets/bg_s_nerd.webp","assets/arena_m_shop.webp","assets/bg_s_mat.webp","assets/tortue_s.webp","assets/hex_s.webp","assets/coin_s.webp","assets/losange_s.webp","assets/totem_s.webp","assets/arena_clean.webp","assets/arena_grim.webp","assets/arena_kawaii.webp","assets/bg/atelier.webp","assets/bg/prez1.webp","assets/bg/prez2.webp","assets/a1.webp","assets/a2.webp","assets/a3.webp","assets/arena.webp","assets/b0.webp","assets/b1.webp","assets/b2.webp","assets/b3.webp","assets/c0.webp","assets/c1.webp","assets/c2.webp","assets/disque.webp","assets/fleche.webp","assets/k0.webp","assets/k1.webp","assets/k2.webp","assets/l1.webp","assets/l2.webp","assets/losange.webp","assets/m0.webp","assets/m1.webp","assets/m2.webp","assets/m3.webp","assets/m4.webp","assets/marteau.webp","assets/n1.webp","assets/n2.webp","assets/pr0.webp","assets/pr1.webp","assets/pr2.webp","assets/pr3.webp","assets/r1.webp","assets/r2.webp","assets/rusty_sprite.webp","assets/tortue.webp"];
self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(()=>self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(
    ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(()=>self.clients.claim()));
});
self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request, {ignoreSearch:true})
    .then(hit => hit || fetch(e.request)));
});
