#!/usr/bin/env node
// CREDITS.md'S MUSIC LIST, BY CONSTRUCTION (SND-MUSIC G1673, SOUND-2026-10-04 ruling s9).
// The shipped music is the catalogue (src/viewer/audio/music_catalogue.json, which the build inlines as
// window.FLYDIY_MUSIC and the credits screen lists); this writes the block between the two markers in CREDITS.md's
// "### Music" subsection from it, line for line the credits screen's (AUDIO_MUSIC.creditLine). GATE AUDIO fails
// when the block and the catalogue differ. The coordinator's prep tool runs it after writing the catalogue.
//   node tools/audio/music_credits.js           -> rewrites the block (prints what changed)
//   node tools/audio/music_credits.js --check   -> exit 1 when CREDITS.md is stale
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..', '..');
const BEGIN = '<!-- MUSIC:BEGIN (generated by tools/audio/music_credits.js from src/viewer/audio/music_catalogue.json - do not edit) -->';
const END = '<!-- MUSIC:END -->';

// the block's text for a catalogue (the credits screen's own line per track, then its page)
function musicBlock(cat, creditLine) {
  const rows = (Array.isArray(cat) ? cat : []).map(t => '- ' + creditLine(t) + (t.source ? ' — ' + t.source : '') +
    ' (`' + t.file + '`; ' + t.contexts.join(', ') + ')');
  return [BEGIN, rows.length ? 'The music that ships (' + rows.length + ' track' + (rows.length === 1 ? '' : 's') + '):' : 'No track ships yet.',
    ''].concat(rows).concat(rows.length ? [''] : []).concat([END]).join('\n');
}
// CREDITS.md with its block replaced (or inserted under "### Music" the first time)
function withBlock(md, block) {
  const a = md.indexOf(BEGIN.slice(0, 18)), b = md.indexOf(END);
  if (a >= 0 && b > a) return md.slice(0, a) + block + md.slice(b + END.length);
  const h = md.indexOf('\n### Music');
  if (h < 0) throw new Error('CREDITS.md has no "### Music" subsection');
  const eol = md.indexOf('\n', h + 1);
  return md.slice(0, eol + 1) + '\n' + block + '\n' + md.slice(eol + 1);
}
function readBlock(md) {
  const a = md.indexOf(BEGIN.slice(0, 18)), b = md.indexOf(END);
  return a >= 0 && b > a ? md.slice(a, b + END.length) : null;
}
module.exports = { musicBlock, withBlock, readBlock, BEGIN, END };

if (require.main === module) {
  const M = require(path.join(ROOT, 'src', 'viewer', 'audio', 'music.js'));
  const cat = JSON.parse(fs.readFileSync(path.join(ROOT, 'src', 'viewer', 'audio', 'music_catalogue.json'), 'utf8'));
  const bad = M.validate(cat);
  if (bad.length) { console.error('the catalogue is invalid:\n  ' + bad.join('\n  ')); process.exit(1); }
  const file = path.join(ROOT, 'CREDITS.md'), md = fs.readFileSync(file, 'utf8');
  const block = musicBlock(cat, M.creditLine), next = withBlock(md, block);
  if (process.argv.includes('--check')) {
    const ok = readBlock(md) === block;
    console.log('CREDITS.md music list: ' + (ok ? 'current' : 'STALE (run node tools/audio/music_credits.js)'));
    process.exit(ok ? 0 : 1);
  }
  if (next !== md) { fs.writeFileSync(file, next); console.log('CREDITS.md: the music list rewritten (' + cat.length + ' tracks)'); }
  else console.log('CREDITS.md: the music list is current (' + cat.length + ' tracks)');
}
