// SND-VOICE (G1626-G1628): Radio Jolene's voice, rendered offline (SOUND-2026-10-04 ruling s12).
//
//   node tools/audio/prep_voice.js [--voice norman]          render every clip -> media/audio/voice/ + the catalogue
//   node tools/audio/prep_voice.js --demo [--voices a,b,c]   the evidence: 3 demo renders per shortlisted voice
//   node tools/audio/prep_voice.js --fetch [--voices a,b]    download the voice models into assets/audio/voices/
//   node tools/audio/prep_voice.js --check                   exit 1 when the catalogue / media / CREDITS are stale
//
// THE CLIPS (G1682: the talk's own words): src/viewer/audio/radio_talk.js's clipLines(places) - every line Radio Jolene's
// break says whole, exactly as its text says it (the ID, the bulletins, the swap corner, the greetings, the time check,
// the pilots' and the marine forecast's phrases, a line per voice_script.json place) -, voice_script.json's extra lines, the AWOS and
// marine vocabulary (src/viewer/audio/voice_model.js's VOCAB: the assembler and the words it needs are one file),
// and per track of src/viewer/audio/music_catalogue.json its back-announce ('ba.<id>': "That was <title>, by
// <artist>."), its title and its artist (VOICE_MODEL.trackKeys). A new catalogue track needs a re-run (GATE AUDIO's
// VOICE_CAT goes red until then).
// THE CHAIN, per clip: Piper (tools/audio/voice_render.py, one python process per run) -> 16-bit WAV at the voice's
// 22 050 Hz -> high-pass 60 Hz -> trimmed (20 ms before the first frame within 45 dB of the clip's loudest, 60 ms
// after the last) -> 5 / 25 ms fades -> levelled to -20 LUFS (BS.1770 K-weighting, 100 ms blocks gated at -70 LUFS
// and -10 LU: short words have no 400 ms block) and never above -1 dBFS -> MP3 mono 48 kb/s (lamejs, a tool
// dependency) -> media/audio/voice/<key>.<h8>.mp3 through _media_lib (content-hashed, owned dir, pruned).
// THE CATALOGUE: src/viewer/audio/voice_catalogue.json = { voice: {the licence record}, clips: { key: { file, text,
// dur } } } - inlined by the build as window.FLYDIY_VOICE; GATE MEDIA reads it like the sound's other catalogues.
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..', '..');
const ML = require(path.join(ROOT, 'tools', '_media_lib.js'));
const X = require(path.join(__dirname, 'excerpt.js'));
const VM = require(path.join(ROOT, 'src', 'viewer', 'audio', 'voice_model.js'));
const RT = require(path.join(ROOT, 'src', 'viewer', 'audio', 'radio_talk.js'));   // G1682: the station's own lines

const SUBDIR = 'audio/voice';
const CAT = path.join(ROOT, 'src', 'viewer', 'audio', 'voice_catalogue.json');
const MUSIC = path.join(ROOT, 'src', 'viewer', 'audio', 'music_catalogue.json');
const SCRIPT = path.join(__dirname, 'voice_script.json');
const CREDITS = path.join(ROOT, 'CREDITS.md');
const VOICES_DIR = path.join(ROOT, 'assets', 'audio', 'voices');   // local (assets/ is gitignored): the models
const EVIDENCE = path.join(ROOT, 'reports', 'evidence', 'SND-VOICE');
const BEGIN = '<!-- VOICE:BEGIN (generated by tools/audio/prep_voice.js from src/viewer/audio/voice_catalogue.json - do not edit) -->';
const END = '<!-- VOICE:END -->';
const TARGET_LUFS = -20, KBPS = 48;

// THE SHORTLIST - each row read off the voice's own MODEL_CARD (copied into reports/evidence/SND-VOICE/cards/).
// Only voices TRAINED FROM SCRATCH on clean data (or fine-tuned from one that was) are here: most Piper English
// voices are fine-tuned from 'lessac' (Blizzard 2013, a research-only licence), so their weights carry it whatever
// their own dataset's licence - see the README's rejected list.
const ENGINE = 'Piper 1.2.0 (rhasspy/piper) + piper-phonemize 1.1.0 - MIT; a render tool only, nothing of it ships';
const MODEL_LIC = 'MIT (the rhasspy/piper-voices repository)';
const MIRROR = id => `https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-${id}.tar.bz2`;
const HF = id => { const [lang, name, q] = id.split('-'); return `https://huggingface.co/rhasspy/piper-voices/tree/main/${lang.split('_')[0]}/${lang}/${name}/${q}`; };
const VOICES = {
  norman: { id: 'en_US-norman-medium', speaker: null, who: 'male, US, low and even', quality: 'medium',
    dataset: 'LibriVox readings by one reader, ~15.5 h, compiled by Bryce Beattie', datasetLicence: 'public domain',
    datasetUrl: 'https://librivox.org', lineage: 'trained from scratch (1200 epochs, medium)' },
  john: { id: 'en_US-john-medium', speaker: null, who: 'male, US', quality: 'medium',
    dataset: 'LibriVox readings by one reader, ~12.5 h, compiled by Bryce Beattie', datasetLicence: 'public domain',
    datasetUrl: 'https://librivox.org', lineage: 'fine-tuned (600 epochs) from en_US-kristin-medium, itself trained from scratch on public-domain LibriVox' },
  libritts: { id: 'en_US-libritts-high', speaker: 856, who: 'male, US (LibriTTS speaker index 856 of 904)', quality: 'high',
    dataset: 'LibriTTS train-clean-360 (Zen et al. 2019; from LibriSpeech, from LibriVox)', datasetLicence: 'CC BY 4.0',
    datasetUrl: 'http://www.openslr.org/60/', lineage: 'trained from scratch on train-clean-360',
    credit: 'LibriTTS corpus by Heiga Zen et al. (Google), CC BY 4.0, http://www.openslr.org/60/' },
  cori: { id: 'en_GB-cori-high', speaker: null, who: 'female, UK', quality: 'high',
    dataset: 'LibriVox readings by one reader, ~24 h, compiled by Bryce Beattie', datasetLicence: 'public domain',
    datasetUrl: 'https://librivox.org', lineage: 'trained from scratch (500 epochs, high)' },
};
// THE CHOICE: G1628 shipped john (the calmest pace, the best ASR round trip); THE USER PICKED NORMAN by ear on the
// listening page (2026-10-04, "norman voice is the best") - G1680 re-rendered everything with it. Another voice is one
// re-run, --voice <name>.
const CHOSEN = 'norman';
const SHORTLIST = ['john', 'norman', 'libritts', 'cori'];

function voiceRecord(name) {
  const v = VOICES[name];
  return { name, id: v.id, speaker: v.speaker, who: v.who, quality: v.quality, engine: ENGINE, modelLicence: MODEL_LIC,
    modelUrl: HF(v.id), dataset: v.dataset, datasetLicence: v.datasetLicence, datasetUrl: v.datasetUrl, lineage: v.lineage,
    credit: v.credit || null, render: { lengthScale: { lines: 1.08, words: 1.0 }, lufs: TARGET_LUFS, kbps: KBPS } };
}

// ---- the clip list ---------------------------------------------------------------------------------------------
function clipList() {
  const S = JSON.parse(fs.readFileSync(SCRIPT, 'utf8'));
  const items = [];
  const RL = RT.clipLines(S.places || {});
  // (a word or two is rendered in a carrier - the clock, the parts of the day, "is favoured," - a greeting is a phrase)
  for (const k in RL) items.push({ key: k, text: RL[k], kind: RL[k].split(/\s+/).length > 2 || /^greet\./.test(k) ? 'line' : 'word' });
  for (const k in S.lines || {}) items.push({ key: k, text: S.lines[k], kind: 'line' });
  for (const k in VM.VOCAB) items.push({ key: k, text: VM.VOCAB[k], kind: 'word' });
  const tracks = fs.existsSync(MUSIC) ? JSON.parse(fs.readFileSync(MUSIC, 'utf8')) : [];
  const seen = new Set(items.map(i => i.key));
  for (const t of tracks) {
    const [ba, ti, ar] = VM.trackKeys(t);
    for (const [key, text, kind] of [[ba, `That was ${t.title}, by ${t.artist}.`, 'line'], [ti, t.title, 'word'], [ar, t.artist, 'word']])
      if (!seen.has(key)) { seen.add(key); items.push({ key, text, kind }); }
  }
  return { items, say: S.say || {} };
}
// the words the voice is given: the 'say' respellings, whole words only
function spoken(text, say) {
  let s = text;
  for (const w in say) s = s.replace(new RegExp('\\b' + w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'g'), say[w]);
  return s;
}

// ---- the signal ------------------------------------------------------------------------------------------------
function readWav(file) {
  const b = fs.readFileSync(file);
  let p = 12, sr = 22050, data = null;
  while (p + 8 <= b.length) {
    const id = b.toString('ascii', p, p + 4), n = b.readUInt32LE(p + 4);
    if (id === 'fmt ') sr = b.readUInt32LE(p + 12);
    if (id === 'data') { data = b.subarray(p + 8, p + 8 + n); break; }
    p += 8 + n + (n & 1);
  }
  const x = new Float32Array(data.length >> 1);
  for (let i = 0; i < x.length; i++) x[i] = data.readInt16LE(i * 2) / 32768;
  return { sr, x };
}
function writeWav(file, x, sr) {
  const b = Buffer.alloc(44 + x.length * 2);
  b.write('RIFF', 0); b.writeUInt32LE(36 + x.length * 2, 4); b.write('WAVEfmt ', 8); b.writeUInt32LE(16, 16);
  b.writeUInt16LE(1, 20); b.writeUInt16LE(1, 22); b.writeUInt32LE(sr, 24); b.writeUInt32LE(sr * 2, 28);
  b.writeUInt16LE(2, 32); b.writeUInt16LE(16, 34); b.write('data', 36); b.writeUInt32LE(x.length * 2, 40);
  for (let i = 0; i < x.length; i++) b.writeInt16LE(Math.max(-32768, Math.min(32767, Math.round(x[i] * 32767))), 44 + i * 2);
  fs.writeFileSync(file, b);
}
function biquad(x, b0, b1, b2, a1, a2) {
  const y = new Float32Array(x.length); let x1 = 0, x2 = 0, y1 = 0, y2 = 0;
  for (let i = 0; i < x.length; i++) { const v = b0 * x[i] + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2; x2 = x1; x1 = x[i]; y2 = y1; y1 = v; y[i] = v; }
  return y;
}
function highpass(x, sr, f0) {
  const w = 2 * Math.PI * f0 / sr, c = Math.cos(w), al = Math.sin(w) / (2 * 0.7071), a0 = 1 + al;
  return biquad(x, (1 + c) / 2 / a0, -(1 + c) / a0, (1 + c) / 2 / a0, -2 * c / a0, (1 - al) / a0);
}
function kweight(x, sr) {   // BS.1770's two stages (excerpt.js's, which does not export them)
  let f0 = 1681.974450955533, G = 3.999843853973347, Q = 0.7071752369554196;
  let K = Math.tan(Math.PI * f0 / sr), Vh = Math.pow(10, G / 20), Vb = Math.pow(Vh, 0.4996667741545416);
  let a0 = 1 + K / Q + K * K;
  const y = biquad(x, (Vh + Vb * K / Q + K * K) / a0, 2 * (K * K - Vh) / a0, (Vh - Vb * K / Q + K * K) / a0, 2 * (K * K - 1) / a0, (1 - K / Q + K * K) / a0);
  f0 = 38.13547087602444; Q = 0.5003270373238773; K = Math.tan(Math.PI * f0 / sr); a0 = 1 + K / Q + K * K;
  return biquad(y, 1, -2, 1, 2 * (K * K - 1) / a0, (1 - K / Q + K * K) / a0);
}
// gated loudness on 100 ms blocks (75 % overlap): the speech's level, short words included
function speechLufs(x, sr) {
  const y = kweight(x, sr), n = Math.max(1, Math.round(0.1 * sr)), hop = Math.max(1, n >> 2), bl = [];
  for (let i = 0; i + n <= y.length || (!bl.length && i === 0); i += hop) {
    let s = 0; const e = Math.min(y.length, i + n); for (let j = i; j < e; j++) s += y[j] * y[j]; bl.push(s / Math.max(1, e - i));
    if (e >= y.length) break;
  }
  const L = ms => -0.691 + 10 * Math.log10(ms + 1e-15);
  let a = bl.filter(m => L(m) > -70); if (!a.length) return -70;
  const rel = L(a.reduce((p, q) => p + q, 0) / a.length) - 10;
  a = a.filter(m => L(m) > rel);
  return L(a.reduce((p, q) => p + q, 0) / a.length);
}
function trim(x, sr) {
  const fr = Math.round(0.005 * sr), db = [];
  for (let i = 0; i < x.length; i += fr) { let s = 0; const e = Math.min(x.length, i + fr); for (let j = i; j < e; j++) s += x[j] * x[j]; db.push(10 * Math.log10(s / Math.max(1, e - i) + 1e-12)); }
  const pk = Math.max(...db), thr = Math.max(-60, pk - 45);
  let a = db.findIndex(d => d > thr), b = db.length - 1; while (b > 0 && db[b] <= thr) b--;
  if (a < 0) return x;
  const n0 = Math.max(0, a * fr - Math.round(0.02 * sr)), n1 = Math.min(x.length, (b + 1) * fr + Math.round(0.06 * sr));
  const y = x.slice(n0, n1), ni = Math.round(0.005 * sr), no = Math.round(0.025 * sr);
  for (let i = 0; i < ni && i < y.length; i++) y[i] *= i / ni;
  for (let i = 0; i < no && i < y.length; i++) y[y.length - 1 - i] *= i / no;
  return y;
}
function level(x, sr) {
  let g = Math.pow(10, (TARGET_LUFS - speechLufs(x, sr)) / 20);
  const pk = X.peak([x]) * g; if (pk > 0.89) g *= 0.89 / pk;
  return x.map(v => v * g);
}
const process1 = (x, sr) => level(trim(highpass(x, sr, 60), sr), sr);

// ---- Piper -----------------------------------------------------------------------------------------------------
function modelOf(name) {
  const v = VOICES[name]; if (!v) throw new Error('unknown voice ' + name + ' (have ' + Object.keys(VOICES).join(', ') + ')');
  const d = path.join(VOICES_DIR, v.id), m = path.join(d, v.id + '.onnx');
  if (!fs.existsSync(m)) throw new Error(`${v.id} is not here - run: node tools/audio/prep_voice.js --fetch --voices ${name}`);
  return { model: m, config: m + '.json', card: path.join(d, 'MODEL_CARD') };
}
function python() {
  for (const py of ['python3', 'python', 'py']) { const r = cp.spawnSync(py, ['-c', 'import piper.voice'], { encoding: 'utf8' }); if (!r.error && r.status === 0) return py; }
  throw new Error('no python with piper - pip install "piper-tts==1.2.0" (MIT; NOT a later one: piper1-gpl is GPL-3.0)');
}
// THE CARRIER: a word of one or two is said inside a comma list and cut out of it (voice_render.py's ALIGNED) - a
// continuing take in the middle ("zero, seven, zero." -> "seven,"), a final take at the end ("zero, zero, seven.");
// a longer item is its own phrase
const CARRY = 'zero';
function carrier(text, kind) {
  const bare = text.replace(/[.,!?;:]+\s*$/, '').trim();
  if (kind !== 'word' || bare.split(/\s+/).length > 2 || /[.,!?;:]/.test(bare)) return { text };
  return /,\s*$/.test(text) || !/[.!?]\s*$/.test(text) ? { text: `${CARRY}, ${bare}, ${CARRY}.`, pick: 1 } : { text: `${CARRY}, ${CARRY}, ${bare}.`, pick: 2 };
}
// render items [{key, text, kind}] with a voice -> Map key -> { x, sr } (processed)
function render(name, items, say) {
  const v = VOICES[name], m = modelOf(name);
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'flydiy_voice_'));
  const job = { model: m.model, config: m.config, speaker: v.speaker, seed: 1, noise_scale: 0.667, noise_w: 0.8, out: tmp,
    items: items.map(it => Object.assign({ key: it.key, length_scale: it.kind === 'line' ? 1.08 : 1.0 }, carrier(spoken(it.text, say), it.kind))) };
  fs.writeFileSync(path.join(tmp, 'job.json'), JSON.stringify(job));
  const r = cp.spawnSync(python(), [path.join(__dirname, 'voice_render.py'), path.join(tmp, 'job.json')], { encoding: 'utf8', maxBuffer: 1 << 26 });
  if (r.status !== 0) throw new Error('voice_render.py: ' + (r.stderr || r.stdout).slice(-2000));
  const out = new Map();
  for (const it of items) { const { sr, x } = readWav(path.join(tmp, it.key + '.wav')); out.set(it.key, { sr, x: process1(x, sr) }); }
  fs.rmSync(tmp, { recursive: true, force: true });
  return out;
}
// a sequence (clip keys and rests) laid end to end, the way AUDIO_VOICE.play schedules it
function assemble(seq, clips) {
  const sr = clips.values().next().value.sr, parts = [];
  for (const s of seq) {
    if (typeof s === 'number') parts.push(new Float32Array(Math.round(s * sr)));
    else { const c = clips.get(s); if (!c) throw new Error('assemble: no clip ' + s); parts.push(c.x); }
  }
  const y = new Float32Array(parts.reduce((a, p) => a + p.length, 0)); let o = 0;
  for (const p of parts) { y.set(p, o); o += p.length; }
  return { x: y, sr };
}

// ---- the evidence ----------------------------------------------------------------------------------------------
// the gusty, low-ceiling day: 270 at 15 gusting 26, 2 SM in light rain and mist, ceiling 600 broken, 1400 overcast,
// minus two over minus four, 29.92
const DEMO_OBS = { timeZ: '1753', wind: { dirDeg: 268, kt: 15, gustKt: 26 }, visSM: 2, wx: ['light_rain', 'mist'],
  sky: [{ cover: 'SCT', ft: 300 }, { cover: 'BKN', ft: 600 }, { cover: 'OVC', ft: 1400 }], tempC: -2, dewC: -4, altInHg: 29.92 };
function demo(names) {
  const { items, say } = clipList();
  const want = new Set(['id.main', 'bulletin.ferry', ...VM.awosClips(DEMO_OBS).filter(k => typeof k === 'string')]);
  const sub = items.filter(i => want.has(i.key));
  fs.mkdirSync(EVIDENCE, { recursive: true });
  const rows = [];
  for (const name of names) {
    const clips = render(name, sub, say);
    const outs = [['station_id', ['id.main']], ['bulletin', ['bulletin.ferry']], ['awos_gusty_low', VM.awosClips(DEMO_OBS)]];
    for (const [what, seq] of outs) {
      const { x, sr } = assemble(seq, clips);
      const file = `${name}_${what}.mp3`;
      fs.writeFileSync(path.join(EVIDENCE, file), X.encodeMp3([x], sr, 64));
      if (process.env.VOICE_WAV) writeWav(path.join(process.env.VOICE_WAV, `${name}_${what}.wav`), x, sr);
      rows.push({ voice: name, what, file, s: +(x.length / sr).toFixed(2), lufs: +X.loudness([x], sr).toFixed(1) });
      console.log('demo', file, (x.length / sr).toFixed(2) + ' s');
    }
    const card = modelOf(name).card, cards = path.join(EVIDENCE, 'cards');
    if (fs.existsSync(card)) { fs.mkdirSync(cards, { recursive: true }); fs.copyFileSync(card, path.join(cards, VOICES[name].id + '.MODEL_CARD.md')); }
  }
  fs.writeFileSync(path.join(EVIDENCE, 'demos.json'), JSON.stringify({ obs: DEMO_OBS, rows }, null, 1) + '\n');
}

// ---- the shipped set -------------------------------------------------------------------------------------------
function creditsBlock(cat) {
  const v = cat.voice;
  const row = `- **Radio Jolene's voice** (\`media/audio/voice/\`, ${Object.keys(cat.clips).length} clips): the Piper voice ` +
    `**${v.id}** (${v.who}; model ${v.modelLicence}, ${v.modelUrl}), trained on ${v.dataset} - ${v.datasetLicence} ` +
    `(${v.datasetUrl}); ${v.lineage}. Rendered offline with ${v.engine}.` + (v.credit ? ` Credit: ${v.credit}.` : '');
  return [BEGIN, row, '', END].join('\n');
}
function withCredits(text, block) {
  if (text.includes(BEGIN.slice(0, 20))) return text.replace(/<!-- VOICE:BEGIN[\s\S]*?<!-- VOICE:END -->/, block);
  const i = text.indexOf('<!-- SFX:END -->');
  if (i < 0) throw new Error('CREDITS.md has no SFX:END to follow');
  const j = i + '<!-- SFX:END -->'.length;
  const head = '\n\n### Radio Jolene\'s voice (`media/audio/voice/`)\n\nA neural text-to-speech voice, rendered OFFLINE into ' +
    'clips (ruling s12): the engine\'s licence and the voice\'s training-data licence are both checked clean ' +
    '(`reports/evidence/SND-VOICE/README.md` has the comparison and the voices turned down). The weather is ' +
    'assembled from recorded words, the way real automated stations work.\n\n';
  return text.slice(0, j) + head + block + text.slice(j);
}
function ship(name) {
  const { items, say } = clipList();
  const clips = render(name, items, say);
  const emitted = [], cat = { voice: voiceRecord(name), clips: {} };
  for (const it of items) {
    const { x, sr } = clips.get(it.key);
    const rel = ML.writeMedia(SUBDIR, it.key.replace(/[^a-z0-9_]+/gi, '_').toLowerCase(), 'mp3', X.encodeMp3([x], sr, KBPS));
    emitted.push(rel);
    cat.clips[it.key] = { file: rel, text: it.text, dur: +(x.length / sr).toFixed(3) };
  }
  const gone = ML.pruneMedia(SUBDIR, emitted);
  if (gone.length) console.log('pruned', gone.length, 'files');
  // one clip per line: a re-render's diff reads as the clips that changed
  const body = Object.keys(cat.clips).map(k => ` ${JSON.stringify(k)}: ${JSON.stringify(cat.clips[k])}`).join(',\n');
  fs.writeFileSync(CAT, '{\n"voice": ' + JSON.stringify(cat.voice) + ',\n"clips": {\n' + body + '\n}\n}\n');
  fs.writeFileSync(CREDITS, withCredits(fs.readFileSync(CREDITS, 'utf8'), creditsBlock(cat)));
  const bytes = [...new Set(emitted)].reduce((a, r) => a + fs.statSync(path.join(ROOT, r)).size, 0);
  const secs = Object.values(cat.clips).reduce((a, c) => a + c.dur, 0);
  console.log(Object.keys(cat.clips).length, 'clips,', secs.toFixed(1), 's,', (bytes / 1048576).toFixed(2), 'MB in media/' + SUBDIR, '(voice ' + name + ')');
}
function check() {
  const bad = [];
  const cat = JSON.parse(fs.readFileSync(CAT, 'utf8'));
  const { items } = clipList();
  for (const it of items) if (!cat.clips[it.key]) bad.push('no clip for ' + it.key);
  for (const k in cat.clips) if (!fs.existsSync(path.join(ROOT, cat.clips[k].file))) bad.push('missing ' + cat.clips[k].file);
  const dir = path.join(ML.MEDIA, 'audio', 'voice'), files = fs.existsSync(dir) ? fs.readdirSync(dir) : [];
  const ref = new Set(Object.values(cat.clips).map(c => c.file.split('/').pop()));
  for (const f of files) if (!ref.has(f)) bad.push('orphan media/audio/voice/' + f);
  if (!fs.readFileSync(CREDITS, 'utf8').includes(creditsBlock(cat))) bad.push('CREDITS.md VOICE block is stale');
  console.log(bad.length ? bad.join('\n') : 'voice: current (' + Object.keys(cat.clips).length + ' clips)');
  process.exit(bad.length ? 1 : 0);
}
function fetchVoices(names) {
  for (const name of names) {
    const v = VOICES[name], d = path.join(VOICES_DIR, v.id);
    if (fs.existsSync(path.join(d, v.id + '.onnx'))) { console.log('have', v.id); continue; }
    fs.mkdirSync(d, { recursive: true });
    const tb = path.join(VOICES_DIR, v.id + '.tar.bz2');
    // the GitHub mirror carries the same onnx (+ ONNX metadata), its json and the MODEL_CARD; Hugging Face's
    // rhasspy/piper-voices is the origin (HF(v.id)) - fetch from there instead when it is reachable
    let r = cp.spawnSync('curl', ['-sSLf', '-m', '600', '-o', tb, MIRROR(v.id)], { stdio: 'inherit' });
    if (r.status !== 0) throw new Error('fetch failed: ' + MIRROR(v.id));
    r = cp.spawnSync('tar', ['xjf', tb, '-C', d, '--strip-components=1', '--exclude=*/espeak-ng-data/*'], { stdio: 'inherit' });
    fs.unlinkSync(tb);
    if (r.status !== 0) throw new Error('untar failed: ' + v.id);
    console.log('fetched', v.id);
  }
}

if (require.main === module) {
  const argv = process.argv.slice(2), arg = k => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : null; };
  const names = (arg('--voices') || SHORTLIST.join(',')).split(',');
  try {
    if (argv.includes('--check')) check();
    else if (argv.includes('--fetch')) fetchVoices(names);
    else if (argv.includes('--demo')) demo(names);
    else ship(arg('--voice') || CHOSEN);
  } catch (e) { console.error(e.message || e); process.exit(1); }
}
module.exports = { VOICES, CHOSEN, SHORTLIST, DEMO_OBS, voiceRecord, clipList, render, assemble, writeWav, speechLufs, trim, spoken, creditsBlock };
