// SND-ASSETS: the shipped recorded sounds (SOUND-2026-10-04 §6.4 / §7.1 step 3, ruling s9).
//
//   node tools/audio/prep_sfx.js [--selection tools/audio/sfx_selection_v1.json] [--check]
//
// For every item of the selection: decode the raw file (assets/audio/raw/freesound/ or raw/nps/, local; CC0, CC BY or
// public domain - LICENCE below; never SA / NC / ND, the user's ruling 2026-10-05), optionally cut to the item's
// `cut: [t0, t1]` seconds (a long field recording: the call chosen by its loudness over the floor), mono, high-pass,
// cut (a bed: the steadiest 32 s; a loop: the steadiest 10 s; a shot: its event, <= 6 s), level (beds and loops to
// -23 LUFS, shots to a -3 dBFS peak capped at -16 LUFS), encode MP3 (beds/loops 96 kb/s, shots 128 kb/s, mono) and
// write media/audio/sfx/<key>_<id>.<h8>.mp3 through _media_lib (content-versioned, owned dir, pruned). Then:
//   src/viewer/audio/sfx_catalogue.json   the manifest the game reads (key -> files, kind, level, licence)
//   tools/audio/shipped.json              the shipped-file ledger GATE AUDIO holds against media/audio/
//   CREDITS.md                            the generated block between SFX:BEGIN / SFX:END (one row per file)
// --check: exit 1 when the catalogue, the ledger or the CREDITS block is stale against media/ (no write).
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const ML = require(path.join(ROOT, 'tools', '_media_lib.js'));
const X = require(path.join(__dirname, 'excerpt.js'));

const SUBDIR = 'audio/sfx';
const CAT = path.join(ROOT, 'src', 'viewer', 'audio', 'sfx_catalogue.json');
const SHIPPED = path.join(__dirname, 'shipped.json');
const CREDITS = path.join(ROOT, 'CREDITS.md');
const BEGIN = '<!-- SFX:BEGIN (generated by tools/audio/prep_sfx.js from tools/audio/sfx_selection_v1.json - do not edit) -->';
const END = '<!-- SFX:END -->';

function highpass(x, sr, f0) {   // RBJ biquad, Q 0.707
  const w = 2 * Math.PI * f0 / sr, c = Math.cos(w), al = Math.sin(w) / (2 * 0.7071);
  const a0 = 1 + al, b0 = (1 + c) / 2 / a0, b1 = -(1 + c) / a0, b2 = b0, a1 = -2 * c / a0, a2 = (1 - al) / a0;
  const y = new Float32Array(x.length);
  let x1 = 0, x2 = 0, y1 = 0, y2 = 0;
  for (let i = 0; i < x.length; i++) { const v = b0 * x[i] + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2; x2 = x1; x1 = x[i]; y2 = y1; y1 = v; y[i] = v; }
  return y;
}
function frameDb(x, sr, frameS) {
  const n = Math.max(1, Math.floor(frameS * sr)), out = [];
  for (let i = 0; i + n <= x.length; i += n) { let s = 0; for (let j = i; j < i + n; j++) s += x[j] * x[j]; out.push(10 * Math.log10(s / n + 1e-12)); }
  return out;
}
// the steadiest window of `dur` seconds: the lowest spread of 0.5 s levels (no event spikes, no dropouts)
function steadiest(x, sr, dur) {
  const total = x.length / sr;
  if (total <= dur + 0.5) return x;
  const db = frameDb(x, sr, 0.5), w = Math.round(dur / 0.5);
  let best = 0, bestScore = Infinity;
  for (let i = 0; i + w <= db.length; i++) {
    const seg = db.slice(i, i + w), m = seg.reduce((a, b) => a + b, 0) / w;
    const sd = Math.sqrt(seg.reduce((a, b) => a + (b - m) * (b - m), 0) / w);
    const score = sd - 0.02 * m;   // prefer steady, then not near-silent
    if (score < bestScore) { bestScore = score; best = i; }
  }
  const n0 = Math.floor(best * 0.5 * sr);
  return x.slice(n0, n0 + Math.floor(dur * sr));
}
// a shot: the main event, from 40 dB under its peak (minus 30 ms) to where it stays 45 dB under, <= 6 s
function event(x, sr) {
  const fs_ = 0.01, db = frameDb(x, sr, fs_);
  let pk = 0; for (let i = 1; i < db.length; i++) if (db[i] > db[pk]) pk = i;
  let a = pk; while (a > 0 && db[a - 1] > db[pk] - 40) a--;
  let b = pk; while (b < db.length - 1 && db[b + 1] > db[pk] - 45) b++;
  a = Math.max(0, a - 3);
  if ((b - a) * fs_ > 6) b = a + Math.round(6 / fs_);
  return x.slice(Math.floor(a * fs_ * sr), Math.min(x.length, Math.floor((b + 1) * fs_ * sr)));
}
function fade(x, sr, inS, outS) {
  const ni = Math.floor(inS * sr), no = Math.floor(outS * sr), n = x.length;
  for (let i = 0; i < ni && i < n; i++) x[i] *= i / ni;
  for (let i = 0; i < no && i < n; i++) x[n - 1 - i] *= i / no;
  return x;
}
function level(x, sr, kind) {
  let g;
  if (kind === 'shot') {
    g = 0.708 / (X.peak([x]) || 1);                              // -3 dBFS peak
    const l = X.loudness([x.map(v => v * g)], sr);
    if (l > -16) g *= Math.pow(10, (-16 - l) / 20);              // capped at -16 LUFS
  } else {
    g = Math.pow(10, (-23 - X.loudness([x], sr)) / 20);
    const pk = X.peak([x]) * g; if (pk > 0.89) g *= 0.89 / pk;   // never above -1 dBFS
  }
  return x.map(v => v * g);
}

// the licences a shipped sound may carry, with how CREDITS names them; anything else (SA, NC, ND, unknown) is refused
const LICENCE = {
  'CC0-1.0': () => 'CC0 1.0',
  'PD-US-NPS': () => 'public domain (a US National Park Service recording)',
};
const licenceName = l => LICENCE[l] ? LICENCE[l]() : /^CC-BY-[34]\.0$/.test(l) ? 'CC BY ' + l.slice(6) : null;
const sourceName = (id, page) => String(id).startsWith('nps-') ? page : `freesound #${id}, ${page}`;

async function prep(sel) {
  const L = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets', 'audio', 'ledger.json'), 'utf8'));
  const emitted = [], cat = [], shipped = [];
  for (const it of sel.items) {
    const s = L.sounds[it.id];
    if (!s || !s.raw) throw new Error(`#${it.id} (${it.key}) is not downloaded - run fs_fetch.js --download --ids ${it.id}`);
    if (!licenceName(s.licence) || /NC|ND|SA/.test(s.licence) || !s.licenceCheck || s.licenceCheck === 'failed') throw new Error(`#${it.id}: licence ${s.licence} not shippable or not re-checked`);
    const { sr, ch } = await X.decode(path.join(ROOT, s.raw));
    let x = ch.length > 1 ? ch[0].map((v, i) => 0.5 * (v + ch[1][i])) : Float32Array.from(ch[0]);
    if (it.cut) x = x.slice(Math.round(it.cut[0] * sr), Math.round(it.cut[1] * sr));
    x = highpass(x, sr, /needs cleaning/.test(it.note || '') ? 90 : 40);
    if (it.kind === 'bed') x = fade(Float32Array.from(steadiest(x, sr, 32)), sr, 0.02, 0.02);
    else if (it.kind === 'loop') x = fade(Float32Array.from(steadiest(x, sr, 10)), sr, 0.02, 0.02);
    else x = fade(Float32Array.from(event(x, sr)), sr, 0.005, 0.03);
    x = level(x, sr, it.kind);
    const mp3 = X.encodeMp3([x], sr, it.kind === 'shot' ? 128 : 96);
    const stem = it.key.replace(/\./g, '_') + '_' + it.id;
    const rel = ML.writeMedia(SUBDIR, stem, 'mp3', mp3);
    emitted.push(rel);
    const row = {
      key: it.key, file: rel, kind: it.kind, durationS: +(x.length / sr).toFixed(2), lufs: +X.loudness([x], sr).toFixed(1),
      id: it.id, title: s.title, author: s.author, licence: s.licence, source: s.page, licenceChecked: s.licenceCheck,
      pick: it.pick,
    };
    cat.push({ key: row.key, file: row.file, kind: row.kind, durationS: row.durationS, lufs: row.lufs });
    shipped.push(row);
    console.log('ok', it.key.padEnd(18), String(it.id).padEnd(7), row.durationS + ' s', row.lufs + ' LUFS', (mp3.length / 1024).toFixed(0) + ' KB', rel);
  }
  const gone = ML.pruneMedia(SUBDIR, emitted);
  if (gone.length) console.log('pruned', gone.join(', '));
  return { cat, shipped };
}

function creditsBlock(shipped) {
  const rows = shipped.map(r => `- \`${r.key}\` — *${r.title}* by **${r.author}** (${sourceName(r.id, r.source)}), ${licenceName(r.licence || 'CC0-1.0')}` +
    (r.pick === 'coordinator' ? ' — coordinator\'s gap fill' : ''));
  return [BEGIN, rows.length ? rows.join('\n') : 'No recorded sound ships yet.', '', END].join('\n');
}
function withCredits(text, block) {
  if (text.includes(BEGIN.slice(0, 18))) return text.replace(/<!-- SFX:BEGIN[\s\S]*?<!-- SFX:END -->/, block);
  const anchor = '### Recorded sounds';
  const i = text.indexOf(anchor);
  if (i < 0) throw new Error('CREDITS.md has no "### Recorded sounds" heading');
  const j = text.indexOf('\n', text.indexOf('\n\n', i) + 2);   // after the section's first paragraph
  return text.slice(0, i) + text.slice(i).replace(/(### Recorded sounds[^\n]*\n\n[\s\S]*?\n)(\n|$)/, (m, a) => a + '\n' + block + '\n\n');
}

(async () => {
  const argv = process.argv.slice(2);
  const si = argv.indexOf('--selection');
  const selFile = si >= 0 ? argv[si + 1] : path.join(__dirname, 'sfx_selection_v1.json');
  const sel = JSON.parse(fs.readFileSync(selFile, 'utf8'));
  if (argv.includes('--check')) {
    const shipped = JSON.parse(fs.readFileSync(SHIPPED, 'utf8'));
    const bad = [];
    for (const r of shipped) if (!fs.existsSync(path.join(ROOT, r.file))) bad.push('missing ' + r.file);
    const want = creditsBlock(shipped), have = fs.readFileSync(CREDITS, 'utf8');
    if (!have.includes(want)) bad.push('CREDITS.md SFX block is stale');
    const dir = path.join(ML.MEDIA, 'audio', 'sfx');
    const files = fs.existsSync(dir) ? fs.readdirSync(dir) : [];
    for (const f of files) if (!shipped.some(r => r.file.endsWith('/' + f))) bad.push('orphan media/audio/sfx/' + f);
    console.log(bad.length ? bad.join('\n') : 'sfx: current (' + shipped.length + ' files)');
    process.exit(bad.length ? 1 : 0);
  }
  const { cat, shipped } = await prep(sel);
  fs.writeFileSync(CAT, JSON.stringify(cat, null, 1) + '\n');
  fs.writeFileSync(SHIPPED, JSON.stringify(shipped, null, 1) + '\n');
  fs.writeFileSync(CREDITS, withCredits(fs.readFileSync(CREDITS, 'utf8'), creditsBlock(shipped)));
  const bytes = shipped.reduce((a, r) => a + fs.statSync(path.join(ROOT, r.file)).size, 0);
  console.log(shipped.length, 'files,', (bytes / 1048576).toFixed(2), 'MB in media/audio/sfx');
})().catch(e => { console.error(e.message || e); process.exit(1); });
