#!/usr/bin/env node
// RADIO JOLENE'S SCRIPTS (G1678, SND-RADIO; SOUND-2026-10-04 §7 / §8 evidence).
//
// The talk generator (src/viewer/audio/radio_talk.js) fed by THE GAME: JOLENE as the game ships it (media/world/jolene
// through tools/island_node.js, the premises fixture tools/fixtures/island_jolene.json composed on it - the real world
// module, its DAY, its CLIMATE, its sea and its aerodromes), under three of the weather panel's own days
// (src/viewer/weather_ui.js PRESETS, copied below with their keys) at three hours. For each: the numbers readGame read
// (and what it had to declare), the tune-in break, then one full rotation of breaks (six) with a back-announce of the
// shipped catalogue's tracks - exactly the text the voice would read.
//
//   node tools/audio/radio_scripts.js        -> reports/evidence/SND-RADIO/README.md + summary.json
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..', '..');
const at = p => path.join(ROOT, p);
const OUT = at('reports/evidence/SND-RADIO');
const R = require(at('src/viewer/audio/radio_talk.js'));
const CAT = JSON.parse(fs.readFileSync(at('src/viewer/audio/music_catalogue.json'), 'utf8'));

// three days of the weather panel (weather_ui.js PRESETS: 'breeze' = DAY_CLOCK's GAME_WIND day, 'front', 'gale'),
// each at an hour that shows the phrasing (afternoon / dawn / morning)
const WEATHERS = [
  { key: 'breeze', title: 'The game\'s day: a light breeze, 16:00 local (DAY_CLOCK GAME_DAY)', localHours: 16,
    day: { wind: { kts: 8, dirDeg: 250, gust: 0.15, refH: 10, breeze: 1 }, oatC: null, qnhPa: null, dewC: null } },
  { key: 'front', title: 'A front an hour out (weather_ui "a front"), 06:10 local', localHours: 6 + 10 / 60, stormInS: 3600,
    day: { wind: { kts: 12, dirDeg: 190, gust: 0.35, refH: 10, terrain: 0.6 }, oatC: 17, qnhPa: 101000, dewC: 13 } },
  { key: 'gale', title: 'A gale (weather_ui "gale"), 07:45 local', localHours: 7.75,
    day: { wind: { kts: 35, dirDeg: 245, gust: 0.5, refH: 10, terrain: 1, aloftK: 1.3, veerDeg: 20 }, oatC: 9, qnhPa: 99200, dewC: 7 } },
];

function main() {
  const { islandWorld } = require(at('tools/island_node.js'));
  const W = islandWorld('jolene', { premises: fs.readFileSync(at('tools/fixtures/island_jolene.json'), 'utf8') });
  if (!W) throw new Error('radio_scripts: no Jolene');
  const tracks = CAT.map(t => ({ title: t.title, artist: t.artist }));
  const md = [], summary = { generated: 'node tools/audio/radio_scripts.js', world: 'jolene (media/world/jolene + tools/fixtures/island_jolene.json)', weathers: [] };
  md.push('# SND-RADIO — Radio Jolene\'s talk, written from the game', '',
    'Generated by `node tools/audio/radio_scripts.js` (do not edit by hand): `src/viewer/audio/radio_talk.js` fed by **Jolene as the game ships it** — ' +
    '`tools/island_node.js` on `media/world/jolene` with the premises `tools/fixtures/island_jolene.json` (the real world module: its DAY, its CLIMATE, ' +
    'its sea, its aerodromes) — under three days of the weather panel (`src/viewer/weather_ui.js` PRESETS). This is the exact text the voice ' +
    '(`speechSynthesis`, rate 0.95, pitch 0.95, Microsoft George en-GB when present) reads, one utterance per segment; the next track plays under it ' +
    'at 16 % and rises to its level over 1.5 s when the voice stops.', '',
    '## Where each number comes from', '',
    '| Spoken | Game source | Notes |', '|---|---|---|',
    '| field name | `world.aerodromes` HOME (`Jolene AFB 13/31`) → designator dropped, "AFB" said "field" | the home strip |',
    '| zulu time | `world.day.utc` | |',
    '| wind | `world.climate.surfaceWind().base` (the 10 m wind, grid frame) → FROM, **true**, by `day.geo.convergenceDeg` (09_climate `bearingToBase` inverted); the gust from `climate.spec.gust` (a front\'s `gustK` included) | no climate → the solver\'s `out.windX/Z` (declared) |',
    '| gusts | peaks `kt·(1+gust)`, lulls `kt·(1−gust)`, reported when they differ by ≥ 10 kt (the METAR rule) | declared rule |',
    '| visibility | `world.climate.haze().surfaceVisM` (Koschmieder, column + layer: what a pilot is told) | no climate → `day.visibilityKm` |',
    '| sky | `day.cloudCoverEff` over `day.cloudBase` (the LCL, 125 m a degree of spread: read as above the field) + upper decks that name a base; oktas → few / scattered / broken / overcast; AWOS sees to 12 000 ft | |',
    '| temperature, dew point | `day.oatC`, `day.dewC` | |',
    '| altimeter | `day.qnhEff` (a front\'s `dQnh` included) → inches of mercury, digit by digit | |',
    '| marine wind, seas | the same wind in compass words, 5 kt steps; seas `2 × world.seaTarget.A` (the wind sea the world raises) | advisory ≥ 23 kt, gale ≥ 34 kt (declared, NWS Alaska) |',
    '| the front\'s outlook | `day.storm` (`phase`, `inS`) and `day.stormSpec` (`windK`, `veerDeg`; 07_day STORM_D\'s 2.2 / 55° when unnamed) | |',
    '| favoured runway | the field\'s designators (`Jolene AFB 13/31`, `02/20`) against the true wind | magnetic variation not carried (declared) |',
    '| one-way strip | `world.aerodromes` with `landHdg` (Tamgas Hill Strip, Jumbo Mine Street, East Point Clearing, Skyline Altiport), their `look` | soft after rain when `day.rh` ≥ 0.85 or a front is passing (declared) |',
    '| sea lane | `world.aerodromes` kind `water` (Annette Dock, Metlakatla Seaplane Base) | |',
    '| part of day, time check | `day.localSeconds` | |', '');
  for (const wx0 of WEATHERS) {
    W.setDay(Object.assign({ date: '2026-06-21', localHours: wx0.localHours, storm: null }, wx0.day));
    if (wx0.stormInS) W.setDay({ storm: { at: W.day.utc + wx0.stormInS, intensity: 1 } });
    if (W.climate.refresh) W.climate.refresh();
    const wx = R.readGame(W);
    const st = { k: 0 };
    const breaks = [R.breakScript(st, wx, [], { tuneIn: true })];
    for (let i = 0; i < 6; i++) breaks.push(R.breakScript(st, wx, [tracks[(2 * i) % tracks.length], tracks[(2 * i + 1) % tracks.length]]));
    const nums = { windKt: +wx.windKt.toFixed(1), windDirT: +wx.windDirT.toFixed(1), gust: wx.gust, visM: Math.round(wx.visM),
      layers: wx.layers.map(l => ({ cover: +l.cover.toFixed(2), baseM: Math.round(l.baseM) })), oatC: +wx.oatC.toFixed(1), dewC: +wx.dewC.toFixed(1),
      qnhPa: Math.round(wx.qnhPa), rh: wx.rh != null ? +wx.rh.toFixed(2) : null, utc: Math.round(wx.utc), local: Math.round(wx.local), seaFt: +wx.seaFt.toFixed(1),
      storm: wx.storm, runways: wx.runways, oneWay: wx.oneWay.map(s => s.name), lanes: wx.lanes, declared: wx.declared };
    summary.weathers.push({ key: wx0.key, title: wx0.title, numbers: nums, breaks });
    md.push('## ' + wx0.title, '',
      'Read off the game: wind **' + nums.windKt + ' kt from ' + nums.windDirT + '° true** (gust factor ' + nums.gust + '), visibility **' + nums.visM + ' m**, ' +
      'sky ' + nums.layers.map(l => 'cover ' + l.cover + ' at ' + l.baseM + ' m').join(', ') + ', **' + nums.oatC + ' °C / dew ' + nums.dewC + ' °C**, QNH **' +
      (nums.qnhPa / 100).toFixed(1) + ' hPa**, rh ' + nums.rh + ', seas ' + nums.seaFt + ' ft' + (nums.storm ? ', a front: ' + nums.storm.phase + ', ' + Math.round(nums.storm.inS / 60) + ' min out' : '') +
      '. Declared: ' + (nums.declared.length ? nums.declared.join('; ') : '**nothing** (every number is the game\'s)') + '.', '');
    breaks.forEach((b, i) => {
      md.push('**' + (i === 0 ? 'Tuning in' : 'Break ' + i) + '**', '');
      for (const s of b) md.push('> *[' + s.kind + (s.key !== s.kind ? ' · ' + s.key : '') + ']* ' + s.text, '>');
      md.pop(); md.push('');
    });
  }
  md.push('## Edge cases (GATE AUDIO RADIO_SCRIPTS holds each)', '',
    '| Case | Spoken |', '|---|---|',
    '| calm (< 1 kt) | ' + R.windAwos({ windKt: 0.4, windDirT: 120, gust: 0 }) + ' |',
    '| gusts (20 kt, gust 0.3: peaks 26, lulls 14) | ' + R.windAwos({ windKt: 20, windDirT: 270, gust: 0.3 }) + ' |',
    '| an 8 kt spread (no gust) | ' + R.windAwos({ windKt: 20, windDirT: 270, gust: 0.2 }) + ' |',
    '| a north wind | ' + R.windAwos({ windKt: 12, windDirT: 2, gust: 0 }) + ' |',
    '| 10 SM and more | visibility ' + R.visWords(37) + ' |', '| 1.6 SM | visibility ' + R.visWords(1.6) + ' |', '| 0.2 SM | visibility ' + R.visWords(0.2) + ' |',
    '| a ceiling below 1000 ft | ' + R.skyAwos({ layers: [{ cover: 0.7, baseM: 800 * 0.3048 }] }) + ' |',
    '| 1200 ft overcast | ' + R.skyAwos({ layers: [{ cover: 1, baseM: 1210 * 0.3048 }] }) + ' |',
    '| nothing under 12 000 ft | ' + R.skyAwos({ layers: [{ cover: 0.9, baseM: 13000 * 0.3048 }] }) + ' |',
    '| −3 °C / −12 °C | temperature ' + R.signed(-3) + ', dew point ' + R.signed(-12) + ' |',
    '| QNH 1013.25 hPa (29.92) | altimeter ' + R.altimeter(101325) + ' |', '| QNH 992 hPa (29.29) | altimeter ' + R.altimeter(99200) + ' |', '');
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'README.md'), md.join('\n'));
  fs.writeFileSync(path.join(OUT, 'summary.json'), JSON.stringify(summary, null, 1) + '\n');
  console.log('radio_scripts: ' + path.relative(ROOT, OUT) + '/README.md, summary.json (' + summary.weathers.length + ' weathers)');
}
if (require.main === module) main();
module.exports = { WEATHERS };
